### PR TITLE
feat(locales.en): extend vehicle

### PR DESCRIPTION
**Pull request by duvall**

### CODE REVIEW

**Review by prisis — APPROVED** [review]

**Review by prisis — CHANGES_REQUESTED** [review]
Can you please change the commit message?

**Comment by duvall** [comment]
> Can you please change the commit message?

You have a preference ?

**Comment by xDivisionByZerox** [comment]
Please don't use exclamation marks ("!") in your commit messages if they are not introducing a breaking change (even if they had to be in another location). Please also note that smilies are generally considered unprofessionally for commit messages (you can still write them in GitHub comments, tho). 
Last but not least, your commit message should caption what you did in this commit. In your case "chore(locales.en): extend vehicle" would be a much better fit.

**Comment by xDivisionByZerox** [comment]
The new commit message should be fine as well, IMO.

**Comment by xDivisionByZerox** [comment]
Please update the test expectation snapshots. To do that run the test script in your project with the update flag `vitest -u` OR delete the according snapshot file (in your case `test\__snapshots__\vehicle.spec.ts.snap`) and run the basic test script `vitest` or `npm run test`. The snapshot file should be updated automatically.

**Review by ST-DDT — APPROVED** [review]

**Pull request merged**
