### PR TITLE
chore(deps): replace vitest v1 deprecations

### PR DESCRIPTION
**Pull request by Shinigami92**
manually crafted PR

closes #2573

not working right now, due to Node v14...

### CODE REVIEW

**Review by xDivisionByZerox — DISMISSED** [review]
I was a bit lost as I didn't see the guide on their website or in the release. I'll leave the [Vitest migration guide](https://vitest.dev/guide/migration.html#migrating-from-vitest-0-34-6) here just in case another reviewer has the same problem as I did.

**Review by ST-DDT — DISMISSED** [review]

**Comment by matthewmayer** [comment]
Will Faker v9 drop node v14 and v16?

Because the vitest migration guide says it requires v18+

**Comment by xDivisionByZerox** [comment]
> Will Faker v9 drop node v14 and v16?
> 
> Because the vitest migration guide says it requires v18+

<s>Yes. #2121 is targeted for milestone v9.</s>

Oh sorry, I did not see the "AND v16". We will only drop v14 as far as I can tell.

[But v16 did reach End-of-Life as well.](https://nodejs.org/en/blog/announcements/nodejs16-eol)

**Comment by ST-DDT** [comment]
IMO we will/should drop v16 support as well.

**Comment by Shinigami92** [comment]
Yes, v16 is already legacy and not supported by Node anymore

**Review by ST-DDT — DISMISSED** [review]

**Comment by ST-DDT** [comment]
@Shinigami92 Could you please fix the merge conflicts here?

**Comment by ST-DDT** [comment]
I fixed the merge conflicts for you. (Totally forgot about this one)

**Review by ST-DDT — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
