### PR TITLE
feat(helpers): arrayElements returns a ts tuple when possible

### LINKED ISSUE #2675: helpers.arrayElements should return a tuple instead of an array
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

`faker.helpers.arrayElements([1, 2, 3], 2)` returns a type of `number[]`, when it should be `[number, number]`

`faker.helpers.arrayElements([1, 2, 3], {min: 2, max: 10})` returns a type of `number[]`, when it should be `[number, number, ...number[]]`

### Minimal reproduction code

_No response_

### Additional Context

_No response_

### Environment Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 21.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.2.1
  npmPackages:
    @faker-js/faker: ^8.4.1 => 8.4.1
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

pnpm

### PR DESCRIPTION
**Pull request by cloud-walker**
Follow up experiment after #2675 discussion

### CODE REVIEW

**Comment by ST-DDT** [comment]
Is this ready for review? There are quite a few unexpected `never`s.

**Comment by cloud-walker** [comment]
No is not ready I guess, but I wanted to publish it anyway to let you see the progress 🤔 

For the `as never` parts, I fear that they may be necessary, as TypeScript may not be smart enough to understand the dynamic nature of the return types. But I'll do some tries to avoid them

**Comment by cloud-walker** [comment]
Made it a draft for now

**Comment by cloud-walker** [comment]
if you wanna leave your impressions in the meanwhile I'll try to address them

**Review by ST-DDT — COMMENTED** [review]
Please add a test, that uses a large count e.g. 100k. These kind of recursive types tend to error our on "deep" recursions.

**Comment by ST-DDT** [comment]
**Team Decision**

We consider this a non goal because

- It can be easily achieved using casts `as [string, string]` which has significantly better performance than recursive types
- Or self crafted methods `return [value1(), value2()] as const`
- You might also want to generate tuples with mixed types `[number, string]` which we would consider dynamic complex objects and thus are not in the scope of faker

**Pull request closed without merging**
