### PR TITLE
chore(release): 8.4.0

### PR DESCRIPTION
**Pull request by xDivisionByZerox**

### CODE REVIEW

**Comment by ST-DDT** [comment]
Should we wait for https://github.com/faker-js/faker/pull/2607 ?
Should we also regenerate the pnpm-lock file as usual?

**Comment by matthewmayer** [comment]
if you think you'll likely do a 8.4.1 no need to wait. If you plan for 8.4.0 to be final pre-9.0.0 release (barring any critical bugfixes) it would be nice to wait.

**Comment by Shinigami92** [comment]
IMO it is fine to wait, so that the docs are directly fine and don't need an extra release

**Comment by Shinigami92** [comment]
https://github.com/faker-js/faker/blob/next/src/modules/finance/index.ts#L379-L612 does not have a `@deprecation` :warning: 
as well as https://github.com/faker-js/faker/blob/next/src/modules/finance/index.ts#L990-L1167
and https://github.com/faker-js/faker/blob/next/src/modules/location/index.ts#L430-L735

In location.longitude the defaults are wrongly documented, (90 instead of 180)

**Comment by xDivisionByZerox** [comment]
> [`next`/src/modules/finance/index.ts#L379-L612](https://github.com/faker-js/faker/blob/next/src/modules/finance/index.ts?rgh-link-date=2024-01-19T18%3A55%3A05Z#L379-L612) does not have a `@deprecation` ⚠️ as well as [`next`/src/modules/finance/index.ts#L990-L1167](https://github.com/faker-js/faker/blob/next/src/modules/finance/index.ts?rgh-link-date=2024-01-19T18%3A55%3A05Z#L990-L1167) and [`next`/src/modules/location/index.ts#L430-L735](https://github.com/faker-js/faker/blob/next/src/modules/location/index.ts?rgh-link-date=2024-01-19T18%3A55%3A05Z#L430-L735)
> 
> In location.longitude the defaults are wrongly documented, (90 instead of 180)

This is what I would put under "if we find anything during the next week", as we discussed in yesterdays meeting. I'd like to release v8.4.0, even if not perfect. Since you already found some unpollished code, we need to release a 8.5.0 as well afterwards.

Opinions on this?

**Review by ST-DDT — DISMISSED** [review]
No pnpm-lock update?

**Comment by xDivisionByZerox** [comment]
> No pnpm-lock update?

I never really understood why we do this in the first place.

The lock file ensures that all dependencies work as expected, if installed under the exact conditions described in the file. Why would I ignore that and update it ON RELEASE to potentially introduce a dependency tree that might be broken?   
Like it partially happened in [the release PR for 8.2.0](https://github.com/faker-js/faker/pull/2478#issuecomment-1763125277). While not breaking the dependency tree, the rebuild introduced parts in the file that resolve in the project not being able to build. You are required to **manually** remove these part. That in itself feels really shady to me.

The lock file should only be updated by renovate or when dependencies are updated manually IMO.

**Review by ejcheng — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
