### PR TITLE
chore: use recommended no-var-requires

### PR DESCRIPTION
**Pull request by Shinigami92**

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]
Is it possible to turn this rule off for tests only?

**Comment by Shinigami92** [comment]
> Is it possible to turn this rule off for tests only?

Yes, should I?

**Comment by Shinigami92** [comment]
> Is it possible to turn this rule off for tests only?

Yes, should I?

**Review by prisis — APPROVED** [review]

**Comment by Shinigami92** [comment]
I discussed with @ST-DDT that we don't want to **implicitly** allow it for tests, we can **explicitly** use the comments

**Pull request merged**
