### PR TITLE
refactor(locale)!: change en_IND to en_IN

### LINKED ISSUE #1354: en_IND locale should be en_IN
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

All other locales use a two letter ISO code for country?

As this would be a breaking change probably en_IND should alias to en_IN

### Minimal reproduction code

```
> faker.locale="en_IN";

Uncaught:
n [Error]: Locale en_IN is not supported. You might want to add the requested locale first to `faker.locales`.
```

```
> faker.locale="en_IND";
'en_IND'
> faker.name.firstName()
'Devi'
```

### Additional Context

_No response_

### Environment Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 43.14 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.17.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 91.0.2
    Safari: 15.5
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

pnpm

### PR DESCRIPTION
**Pull request by wael-fadlallah**
For #1354

### CODE REVIEW

**Comment by Shinigami92** [comment]
@wael-fadlallah looks like you didn't changed first to the `next` / default branch

**Review by Shinigami92 — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Comment by matthewmayer** [comment]
Can en_IND be made an alias (throwing a warning) for en_IN for v8 and then removed completely in v9?

**Comment by Shinigami92** [comment]
> Can en_IND be made an alias (throwing a warning) for en_IN for v8 and then removed completely in v9?

@matthewmayer Please open a PR to tackle this, or open a new issue so we can make that visible and not miss it before releasing v8.0.
A comment in a already closed/merged PR will likely go under and unseen :warning:

**Comment by matthewmayer** [comment]
> > Can en_IND be made an alias (throwing a warning) for en_IN for v8 and then removed completely in v9?
> 
> @matthewmayer Please open a PR to tackle this, or open a new issue so we can make that visible and not miss it before releasing v8.0. A comment in a already closed/merged PR will likely go under and unseen ⚠️

sure https://github.com/faker-js/faker/issues/1454

**Pull request merged**
