### PR TITLE
refactor(locale): improve zh_CN vehicle manufacturers

### PR DESCRIPTION
**Pull request by Heuluck**
Use the correct translations, and add some vehicle manufacturers to zh_CN

### CODE REVIEW

**Review by ST-DDT — CHANGES_REQUESTED** [review]
Please run `pnpm run preflight` once and commit the changes.

**Review by ST-DDT — APPROVED** [review]
Thank you for your PR and quick fixes ❤️ .

I checked with Google translate and it looks good to me, but I would love to have a native speaker review this as well.

**Comment by Heuluck** [comment]
It was my first pr so thanks for helping me correcting my mistake

**Review by xDivisionByZerox — APPROVED** [review]
Confirmed the changes as well by using a translation program.
In the worst case (we don't find any native speaker), I'd say this is good enought and can be changed by later contributors if values are undesired.

**Comment by ST-DDT** [comment]
Thanks for your contribution. ❤️ 

The changes will be included in the next release, but we don't a release schedule for it yet.

**Pull request merged**
