### PR TITLE
fix: add "types" field

### LINKED ISSUE #176: Typescript error due to missing "types" field
### Describe the bug

Typescript gives the error:

```
> tsc

node_modules/.pnpm/@faker-js+faker@6.0.0-alpha.3/node_modules/@faker-js/faker/index.ts:4:1 - error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.

4 export = faker;
  ~~~~~~~~~~~~~~~


Found 1 error.
```

This is fixed by adding the "types" field:

From:

```json
{
  "name": "@faker-js/faker",
  "version": "6.0.0-alpha.3",
  "description": "Generate massive amounts of fake contextual data",
  "repository": {
    "type": "git",
    "url": "https://github.com/faker-js/faker.git"
  },
  "license": "MIT",
  "main": "index.js",
  "scripts": {}
}
```

To:

```json
{
  "name": "@faker-js/faker",
  "version": "6.0.0-alpha.3",
  "description": "Generate massive amounts of fake contextual data",
  "repository": {
    "type": "git",
    "url": "https://github.com/faker-js/faker.git"
  },
  "license": "MIT",
  "main": "index.js",
  "types": "index.d.ts",
  "scripts": {}
}
```

### Reproduction

https://github.com/pabloszx/faker-error-types

### Additional Info

   "@faker-js/faker": "6.0.0-alpha.3"

### PR DESCRIPTION
**Pull request by PabloSzx**
closes #176

### CODE REVIEW

**Review by prisis — APPROVED** [review]

**Review by MilosPaunovic — APPROVED** [review]

**Comment by Shinigami92** [comment]
Why does it not _auto-resolve_ this file when it is next to the `index.js`?

**Comment by PabloSzx** [comment]
> Why does it not _auto-resolve_ this file when it is next to the `index.js`?

because an `index.ts` is alongside, and the "index.ts" has priority over "index.d.ts", which is not the desired behavior in this case

**Comment by Shinigami92** [comment]
> because an `index.ts` is alongside, and the "index.ts" has priority over "index.d.ts", which is not the desired behavior in this case

😯
Would this then be fixed by #177?
So if I understand correctly, then we don't need this field.

**Review by import-brain — APPROVED** [review]

**Review by Shinigami92 — CHANGES_REQUESTED** [review]
See my comment: https://github.com/faker-js/faker/pull/177#issuecomment-1013922219

**Comment by PabloSzx** [comment]
> See my comment: https://github.com/faker-js/faker/pull/177#issuecomment-1013922219

Yes it will be fixed by this PR, you can use the reproduction repo and add the types field manually and the error is fixed

**Comment by Shinigami92** [comment]
So I will close this, cause we already plan to merge #177 soon™

**Comment by PabloSzx** [comment]
> So I will close this, cause we already plan to merge #177 soon™

This is #177, what do you mean

**Comment by Shinigami92** [comment]
Sorry for confusing :laughing: 
I mean #173

**Comment by PabloSzx** [comment]
#173 doesn't fix the issue, reopen this pr

**Comment by PabloSzx** [comment]
> #173 doesn't fix the issue, reopen this pr

That PR still ships index.ts which has the same error

**Comment by Shinigami92** [comment]
After that change https://github.com/faker-js/faker/pull/173#pullrequestreview-853708363 it will

**Pull request closed without merging**
