### PR TITLE
refactor: restore en_IND

### LINKED ISSUE #1454: en_IND should be an alias for en_IN in v8
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

https://github.com/faker-js/faker/issues/1354 was fixed in https://github.com/faker-js/faker/pull/1448 where the en_IND locale was renamed to en_IN

However to avoid an unnecessary breaking change, in v8 en_IND should be kept as an alias for en_IN, emitting a warning if used, and only completely removed in v9

### Minimal reproduction code

_No response_

### Additional Context

_No response_

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 43.42 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 91.0.2
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #1454

### CODE REVIEW

**Comment by Shinigami92** [comment]
@ST-DDT Do I also need to alias the locales definition and therefore add `'en_IND'` (the string locale **key**)
This might be unnecessary because of
- #1735

**Comment by ST-DDT** [comment]
I'm not sure what you are intent to say. Let's wait for the PR to get merged.

**Comment by ST-DDT** [comment]
#1735 is merged, so this is no longer blocked.

**Comment by matthewmayer** [comment]
As part of this upgrading.html can be updated to reflect this is no longer breaking (remove or move to second section).

**Comment by Shinigami92** [comment]
I will update this PR after

- #1748

was merged

**Review by ST-DDT — DISMISSED** [review]

**Review by matthewmayer — CHANGES_REQUESTED** [review]
upgrading.html can be updated to reflect this is no longer breaking (remove or move to second section).

**Review by matthewmayer — APPROVED** [review]

**Review by matthewmayer — DISMISSED** [review]
Doesn't seem to expose the fakerEN_IND object?
```
const {fakerEN_IND, fakerEN_IN} = require("@faker-js/faker")

fakerEN_IN.person.fullName()
>> 'Udit Patel'

fakerEN_IND.person.fullName()
>> Uncaught TypeError: Cannot read property 'person' of undefined
```

**Comment by Shinigami92** [comment]
@ST-DDT what do I need to do here to handle this edge case?

**Comment by ST-DDT** [comment]
Was it ever exposed like that?

**Comment by ST-DDT** [comment]
IMO the sole thing that should work is the original import. We shouldnt add new imports just to deprecate them immediately.

**Comment by Shinigami92** [comment]
> Was it ever exposed like that?

It was only exposed as `@faker-js/faker/locale/en_IND`

So yes you are right
```ts
import { faker } from '@faker-js/faker/locale/en_IND';

console.log(faker.person.firstName());
```
works fine

**Comment by matthewmayer** [comment]
Hmm it kinda feels like a double breaking change if you previously had

```
faker.locale = "en_IND"
faker.foo.bar()
```

You have to figure out to change that to

```
fakerEN_IN.foo.bar()

```

**Comment by ST-DDT** [comment]
> Hmm it kinda feels like a double breaking change if you previously had
> 
> ```
> faker.locale = "en_IND"
> faker.foo.bar()
> ```
> 
> You have to figure out to change that to
> 
> ```
> fakerEN_IN.foo.bar()
> ```

Sure, but in order to know that migration step, you have to go to the migration guide to lookup the new naming convention anyway.
If you don't find the expected import you will probably search for EN_IND in that document and find the information that it has been renamed (or just check the list of available imports via auto completion).
As a compromise, we could add a hint to the migration guide to clarify the new locale/faker import names.

````txt
You can use our pre-built faker instances using the `fakerEN_IN` import.
````

**Review by ST-DDT — APPROVED** [review]

**Comment by matthewmayer** [comment]
Sounds good.

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
