### PR TITLE
chore: remove disturbing image from README

### PR DESCRIPTION
**Pull request by ST-DDT**
The image shown on the [README](https://github.com/faker-js/faker/blob/95d0765caaf882c87064cbbeae5399a2582b7f9d/README.md#-modules) is disturbing and needs to be removed ASAP.

<details>
<summary>Screenshot (Click to show)</summary>

grafik

</details>

The image is static and no longer random.
~~I assume this is intentional from loremflickr to prevent the usage on github.~~ 
Correction: Github Image Cache + Bad Luck
Reproducible in Firefox (normal, mobile and private mode), Chrome.

I also consider removing loremflickr from our image providers entirely, since having that image in a presentation with a customer is an absolute no go 🙅 .

### CODE REVIEW

**Comment by xDivisionByZerox** [comment]
IDK man. I get a cat. Cant be as static as you say.
image

**Comment by ST-DDT** [comment]
I had to reload the page on FF-mobile private mode to get the bad one. So I'm not exactly sure, what actually is the condition for getting the image, but I get it on different devices, OSes, browsers on the first and subsequent visits.

**Review by ejcheng — APPROVED** [review]

**Comment by ejcheng** [comment]
> IDK man. I get a cat. Cant be as static as you say. image

I'm getting the disturbing image

**Review by xDivisionByZerox — APPROVED** [review]

**Comment by pkuczynski** [comment]
I am getting it too :)

**Review by pkuczynski — APPROVED** [review]

**Review by pkuczynski — APPROVED** [review]

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
PS: Github was showing me 500, which lead to 3 approvals :D

**Comment by pkuczynski** [comment]
PS: Github was showing me 500, which lead to 3 approvals :D

**Comment by matthewmayer** [comment]
Maybe contact the creator of LoremFlickr https://github.com/MastaBaba also?

It looks like it pulls images directly from the Flickr API rather than a fixed set of images, which seems risky, as there's nothing to prevent a badly tagged disturbing image on Flickr from creeping into the results.

https://github.com/MastaBaba/LoremFlickr-2

So I would agree to remove loremflickr as a provider, seems too much like a potential pitfall.

**Review by Shinigami92 — APPROVED** [review]

**Comment by Shinigami92** [comment]
There is something really weird
When I hover over the image, it does not link to `https://loremflickr.com/640/480/cats` but `https://camo.githubusercontent.com/2b0b0e6a1e2aa9985824e1d254f7e12789f8fb76399da5c7ee561fed280e50f8/68747470733a2f2f6c6f72656d666c69636b722e636f6d2f3634302f3438302f6361747` + `3`

<details>
<summary>Details</summary>

image
^^^^^

</details>

Did we somehow got hacked? How is this even possible?
image

The input for this was

https://github.com/faker-js/faker/blob/2b84b3389a2719e0f365055990a51673acd07ac9/README.md?plain=1#L106

So just ``

**Comment by Shinigami92** [comment]
🤯

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache

More and more I assume we got somehow hacked!
We should try to purge the cache via the provided steps (I'm in some meetings right now...)
And if this does not help we should contact GitHub support and at least tell them so they know

In worst case the new image we are now showing will be hacked as well in the same way...

**Comment by Shinigami92** [comment]
F*ck...

I run
```
curl -X PURGE https://camo.githubusercontent.com/{the camo id}
```

and it worked!

image

This was a personal attack on Faker!!! LoremFlickr is **NOT** involved at all!!! ⚠️

**Comment by ST-DDT** [comment]
From the linked article I get the impression that Github caches external images when they md2html that page (once).
So I assume that either a very unfortunately tagged image was returned during that time ~~or the anonymising GH proxy is on some kind of penalty/block/overuse list.~~

Edit: since the cache purge solved this, I assume it has been bad luck.

**Comment by xDivisionByZerox** [comment]
> More and more I assume we got somehow hacked!

Why and how do you get that impression?! You even provided a documentation source that states why that (the content tag) happens.

> This was a personal attack on Faker!!! LoremFlickr is NOT involved at all!!! ⚠️

Now you are overdramatizing. It's bad luck. For someone maintaining a library which is all about odds I'm a bit disappointed hearing such statements.
LoremFlickr is so far involved that they simply have "badly" tagged images every now and than. Again, I'm if you provide massive image sets, it's simply a numbers game that such things happen...

**Comment by matthewmayer** [comment]
If you do a reverse image search you can see that image is on Flickr

So my guess is
- someone tags macabre image as cats as a joke on Flickr 
- loremFlickr pulls in "cat" image via Flickr api
- Flickr admins removes tag
- github camo caching causes image to get cached for longer than expected

**Comment by Shinigami92** [comment]
Very interesting
That calms me down a bit

We should still message the Flickr author later on then

**Comment by matthewmayer** [comment]
maybe could add a warning in the documentation like 

"The images are fetched from an external service outside the control of Faker, and could occasionally contain URLs which point to unexpected or offensive images."

**Comment by ST-DDT** [comment]
Let's continue the discussion here: https://github.com/faker-js/faker/issues/1783

**Pull request merged**
