### PR TITLE
docs: update Faker.js logo and refs

### PR DESCRIPTION
**Pull request by damienwebdev**

### CODE REVIEW

**Review by Shinigami92 — APPROVED** [review]

**Comment by GreatWizard** [comment]
JPG are best for photo.
Logo like this are better rendered in png. Do you have it?

**Comment by prisis** [comment]
Maybe we can create a svg out of it, than we dont have problem with sizes

**Comment by damienwebdev** [comment]
I am not skilled enough to make an SVG, maybe someone else is?

**Comment by JessicaSachs** [comment]
@damienwebdev I put this Figma board together last night https://www.figma.com/file/iQ2guHOrd8HGKBiGCMINP7/Faker-Design?node-id=0%3A1

It's the font from the old faker.js logo. I did one of those fancy reverse-font lookup things and put this together. 

I'm using those logos in my docs PR #80

**Comment by damienwebdev** [comment]
Closing this until we have a revised logo.

**Pull request closed without merging**
