### PR TITLE
fix(location): use IANA standard for timezone

### LINKED ISSUE #734: Use IANA standard for timezone
In documentation, please refer to standard you are using for generating timezones. 
E.g. `Asia/Rangoon` is not an official [IANA code](https://www.iana.org/time-zones), but is a "symlink" to `Asia/Yangon`. 
Thanks

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #734

I generated this using a library which already parses the official tzdb data and therefore contains all valid tz names.

```
npm i @vvo/tzdb

const {timeZonesNames} = require("@vvo/tzdb")
console.log(JSON.stringify(timeZonesNames, null, 2))
```

I also deleted the list from other locales except `en` since these were just duplicates of the global list (in theory 
another locale might want to have its own list, e.g. en_AU could return only Australian timestamps?)

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]
For now this is okay, but in #735 we need to move it out of `en` into a global thingy

**Comment by xDivisionByZerox** [comment]
> For now this is okay, but in #735 we need to move it out of `en` into a global thingy

I was questioning if I should mark that in this PR. @matthewmayer do you want to do that as well? Otherwise I could do that, should be easy enough.

**Comment by matthewmayer** [comment]
maybe locales might want to override this in future? Like en_AU could return only Australian timezones

**Comment by Shinigami92** [comment]
> maybe locales might want to override this in future? Like en_AU could return only Australian timezones

@matthewmayer => #735

**Pull request merged**
