### PR TITLE
chore: cleanup and sort gitignore

### PR DESCRIPTION
**Pull request by pkuczynski**
Cleans up gitignore from items not relevant to our project. Sorts the rest in alphabetical order so it's easier to find items

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]
This doesn't matter much to me. So I'm fine with either way.

**Comment by pkuczynski** [comment]
> This doesn't matter much to me. So I'm fine with either way.

When adding the eslint cache, I was planning to add `.eslintcache` to gitignore and I had to scan it manually to see if it contains it. Quite annoying. That's how I come up with this PR :)

**Review by Shinigami92 — COMMENTED** [review]
Please add some comments and reasons why something is ignored
I also prefer grouping stuff together like it was before

**Comment by pkuczynski** [comment]
> Please add some comments and reasons why something is ignored
> I also prefer grouping stuff together like it was before

Sections mean that things are not in alphabetical order. And all the entries should be quite obvious why they are there, right? Not sure what kind of comments would you like me to add, as they didnt had comments before (except section titles)...

**Comment by prisis** [comment]
> This doesn't matter much to me. So I'm fine with either way.
> 
> When adding the eslint cache, I was planning to add `.eslintcache` to gitignore and I had to scan it manually to see if it contains it. Quite annoying. That's how I come up with this PR :)

Why not use command + f? and search for it?

**Comment by pkuczynski** [comment]
> Why not use command + f? and search for it?

Now they all fit on one page, so no need to search and see if there are any conflicts, exclusions, etc. Gitignire can also have exceptions, right?

> I would have the default node gitignore and added stuff to it, than removing all this

Why would we have docosaurus or meteor entries if we dont use them? Lean is more readable.

**Comment by Shinigami92** [comment]
Yeah, I mean to group them at least in sections like
- logs
- pkg managers
- mac
- coverage / tests
- ...

I'm also more of @prisis side to use a verbose version and use the node gitignore as a base and just extend that (https://github.com/github/gitignore/blob/main/Node.gitignore)
It doesn't hurt that much

**Review by import-brain — APPROVED** [review]

**Comment by prisis** [comment]
I going to close this ticket, the gitignore will just stay at its is :), sorry!

**Pull request closed without merging**
