### PR TITLE
fix: lowercase email

### LINKED ISSUE #226: Lowercase email
### Clear and concise description of the problem

As the email is the combination of random fname and lname, the produced email returns a capitalised email.

### Suggested solution

Just make the output as lowercase before return.

### Alternative

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pkuczynski**
fixes #226

### CODE REVIEW

**Comment by Shinigami92** [comment]
Please see https://github.com/faker-js/faker/issues/226#issuecomment-1016622618

**Comment by pkuczynski** [comment]
I saw that comment, but you haven't closed the issue, so I thought I could provide a quick fix...

**Comment by Shinigami92** [comment]
> I saw that comment, but you haven't closed the issue, so I thought I could provide a quick fix...

Yeah okay sorry for that :sweat_smile: 
I just waited on some additional responsed, would not have thought that someone would just create a PR without asking

**Comment by pkuczynski** [comment]
I learned that and added comments here and there offering my help :)

**Pull request closed without merging**
