### PR TITLE
test: migrate datatype to test snapshots

### PR DESCRIPTION
**Pull request by ST-DDT**
We should migrate from our old inline seeded tests to using test snapshots, as these are way easier to update.
I plan to update the other modules as well, but this one is the first in case something needs to be changed.

### CODE REVIEW

**Comment by xDivisionByZerox** [comment]
I'm sorry but in what world is this easier to maintain? By changing any label in the entire test chain, you have an invalid expectation key.  

Also since every snapshot value is a string, prettier can't apply the style guide correctly. Or am I missing something?

Can you please elaborate on how this helps maintainability wise?

**Comment by Shinigami92** [comment]
Snapshots can be updated by just using [`--update`](https://vitest.dev/guide/cli.html#options)

But yeah, I was not aware that it just uses strings and therefore we loose the types 🤔

**Comment by xDivisionByZerox** [comment]
Ok, I didn't know there was such an option. Thought the migration was done by hand.

**Comment by Shinigami92** [comment]
> Ok, I didn't know there was such an option. Thought the migration was done by hand.

That's the whole point of using snapshots 😉

**Comment by Shinigami92** [comment]
I would prefer to have all tests migrated in one PR so it is only one commit in main branch history. You could create commits test by test to make review easier.

**Review by import-brain — DISMISSED** [review]

**Review by xDivisionByZerox — DISMISSED** [review]

**Review by Shinigami92 — DISMISSED** [review]

**Review by import-brain — DISMISSED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Review by import-brain — APPROVED** [review]

**Pull request merged**
