### PR TITLE
refactor: improve groupBy

### PR DESCRIPTION
**Pull request by ST-DDT**
Adds a value mapping function to `groupBy`.

Intended for #2530

### CODE REVIEW

**Review by xDivisionByZerox — COMMENTED** [review]
I feel like this missed the point of "grouping" by a key. This function would then break the single responsibility principle.

Note that the following polifills (which this function was inspired by) do not include a value mapper as well:
- [Object.groupBy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy)
- [Map.groupBy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/groupBy)
- [Array.prototype.groupToMap](https://tc39.es/proposal-array-grouping/#sec-map.groupby)

**Comment by ST-DDT** [comment]
In the Java world they noticed quite early ([Java 8](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#groupingBy-java.util.function.Function-java.util.function.Supplier-java.util.stream.Collector-)), that there is a need to give the user the ability to also process/transform the value.
Common usecases include wrapper shedding, which is the reason why I added the parameter in the first place.

````ts
groupBy(
  [
    [1, "someValue"],
    [2, "blub"],
    [1, "anotherone"]
  ], 
  (e) => e[0],
  (e) => e[1]
);
````

=> 

````ts
{
  1: ["someValue", "anotherone"],
  2: ["blub"]
}
````

I can explain this in more detail in the next team-meeting if you would like to.

**Comment by xDivisionByZerox** [comment]
Please add the behaviour to the indended place as #2530 is already merged. I'm fine with keeping the additional utility.

**Review by xDivisionByZerox — DISMISSED** [review]

**Comment by xDivisionByZerox** [comment]
"Off-topic" question: Should we have tests for our internal function?

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
