### PR TITLE
fix(location): Dutch postal codes can never start with '0'

### PR DESCRIPTION
**Pull request by RobinvanderVliet**

### CODE REVIEW

**Review by matthewmayer — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
If you fix something please include a link that can be used for verification if possible.

**Comment by ejcheng** [comment]
> If you fix something please include a link that can be used for verification if possible.

Not too sure if this is good enough verification but it's what I found: https://stackoverflow.com/questions/17898523/regular-expression-for-dutch-zip-postal-code#:~:text=As%20an%20aside%3A%20Dutch%20postal%20codes%20never%20start%20with%20a%20zero.

**Review by ejcheng — APPROVED** [review]

**Comment by ST-DDT** [comment]
> > If you fix something please include a link that can be used for verification if possible.
> 
> Not too sure if this is good enough verification but it's what I found: [stackoverflow.com/questions/17898523/regular-expression-for-dutch-zip-postal-code#:~:text=As%20an%20aside%3A%20Dutch%20postal%20codes%20never%20start%20with%20a%20zero](https://stackoverflow.com/questions/17898523/regular-expression-for-dutch-zip-postal-code#:~:text=As%20an%20aside%3A%20Dutch%20postal%20codes%20never%20start%20with%20a%20zero).

Well, there is always https://github.com/validatorjs/validator.js/blob/master/src/lib/isPostalCode.js

**Comment by matthewmayer** [comment]
Wikipedia generally explains postcodes well

https://en.wikipedia.org/wiki/Postal_codes_in_the_Netherlands?wprov=sfti1

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
