### PR TITLE
test: remove JSON.stringify wrapper around faker.seed() in tests descriptions

### PR DESCRIPTION
**Pull request by pkuczynski**
I am not sure why we had those `JSON.stringify` @Shinigami92?

### CODE REVIEW

**Comment by xDivisionByZerox** [comment]
They were wrapped due to `faker.seed` being able to return an array of numbers if one is used as input value. But we don't do that so this should be fine.

**Review by xDivisionByZerox — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]
I think it's okay.

**Comment by pkuczynski** [comment]
> They were wrapped due to `faker.seed` being able to return an array of numbers if one is used as input value. But we don't do that so this should be fine.

1. `seed(seed?: number): number;`
2. `console.log(`${[1, 2, 3]}`) // '1,2,3'

:)

**Comment by xDivisionByZerox** [comment]
> console.log(`${[1, 2, 3]}`) // '1,2,3'

And that's why `JSON.stringif` was used for arrays. Because this output this sh*t. I mean it works but doesn't provide clarity. You could also have written ```console.log(`${seed1}, ${seed2}, ${seed3}`)```.
One the other side, JSON gives me a nicely formatted array `console.log(JSON.stringify([1,2,3])) // [1,2,3]`.

But it doesn't matter since we know now from the signature overload if the return value will be an array or not and can act accordingly.

**Comment by pkuczynski** [comment]
From the signature we know it's never an array :)

**Comment by xDivisionByZerox** [comment]
https://github.com/faker-js/faker/blob/5ea8252f727e2e577c2adca9650ac8f24a171632/src/faker.ts#L242-L244

It literally has `number` **OR** `number[]` as return type.

**Comment by pkuczynski** [comment]
Indeed! I haven't notice the overload because of jsdoc, sorry :)

**Review by import-brain — APPROVED** [review]

**Pull request merged**
