### PR TITLE
refactor(locale): enhance en vehicle manufacturers

### LINKED ISSUE #3186: Extension to Vehicle Manufacturers List
As an Extension to Vehicle Manufacturers list over added by @matthewmayer in #2881.

Adding some more Manufacturers available in India from various geolocations: India, China, Czech to the data would be beneficial.

Examples:

Indian Manufacturers:
- Tata Motors
- Mahindra & Mahindra

India-Japan tie up in India:
- Maruti Suzuki

China:
- MG Motor

Czech:
- Skoda

I have added a PR as well, if issue is approved, we can use that.

### PR DESCRIPTION
**Pull request by suyashgulati**
This resolves #3186

### CODE REVIEW

**Review by ST-DDT — COMMENTED** [review]
I'm not familiar with (these) manufactures.
Are these actually in use in primarily English countries?

**Comment by ST-DDT** [comment]
If these are more common in specific countries, then maybe we should use a country specific locale for them instead?

**Comment by matthewmayer** [comment]
Skoda is fairly popular in UK. #12 here. 

https://www.best-selling-cars.com/britain-uk/2023-full-year-britain-best-selling-car-brands-in-the-uk/

The others are popular in India. 

https://www.detailingdevils.com/blog/top-9-automobile-brands-in-india

Not sure the "motors" etc is needed in Tata Motors. 

Eg you'd say "Tata Nexon" not "Tata Motors Nexon"

**Review by xDivisionByZerox — DISMISSED** [review]

**Comment by suyashgulati** [comment]
> Not sure the "motors" etc is needed in Tata Motors.
> 
> Eg you'd say "Tata Nexon" not "Tata Motors Nexon"

Though I understand that normally cars are named Tata Nexon, but TATA as standalone is a group of companies Tata Group which consists various other companies, like Tata Steel, Tata Consultancy Services etc..

https://en.wikipedia.org/wiki/Tata_Motors

**Review by Shinigami92 — DISMISSED** [review]

**Comment by matthewmayer** [comment]
But if listed with a list of other manufacturers eg on a car insurance website I'd expect to just see "Tata" or "MG". 

image

Also we combine the "manufacturer" and "model" to give the "vehicle" method so I think we should stick to short names.

**Comment by suyashgulati** [comment]
> But if listed with a list of other manufacturers eg on a car insurance website I'd expect to just see "Tata" or "MG".

Nice! thats a good find.

> Also we combine the "manufacturer" and "model" to give the "vehicle" method so I think we should stick to short names.

With this I agree short names should be preferable. I will make the change.

**Review by ST-DDT — APPROVED** [review]

**Review by matthewmayer — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
