### PR TITLE
🔥 remove FUNDING.yml

### PR DESCRIPTION
**Pull request by ctcpip**

### CODE REVIEW

**Comment by damienwebdev** [comment]
As described here: https://github.com/faker-js/faker/discussions/56 we will not be progressing with this.

**Comment by ctcpip** [comment]
ah, I looked for an existing issue, but didn't see any.  I haven't interacted much with the `discussions` feature.  👀   thanks

**Comment by ctcpip** [comment]
@damienwebdev - perhaps we should add a comment to the file for future visitors, maybe include a link to that discussion?

**Comment by damienwebdev** [comment]
I don't think we should litter the codebase with externalities, just like issues are for bugs, features, etc. If people want further information, they can look to previous issues/discussions.

**Comment by damienwebdev** [comment]
cc: @ctcpip https://github.com/faker-js/faker/pull/110

**Pull request closed without merging**
