### PR TITLE
refactor(locale): rename company affix files

### LINKED ISSUE #1574: Rename company.suffix definition to company.legal_entity_type
### Clear and concise description of the problem

The company suffixes currently refer to the company/business entity type (not sure about this term) and not a real suffix in the usual sense.

### Suggested solution

We should rename the `suffix` to `type` (both the definitions and method).

### Alternative

_No response_

### Additional context

Discovered here: https://github.com/faker-js/faker/pull/1573

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes #1574

- #1574

This PR renames the company `prefix` and `suffix` files to `category`/`legal_entity_type` respectively.

### CODE REVIEW

**Comment by ST-DDT** [comment]
I was unable to identify which part is the category or legal_entity_type in `lv` and `ru`.
Maybe they have the `legal_entity_type` sometimes as prefix and sometimes as suffix?

- https://github.com/faker-js/faker/tree/next/src/locales/lv/company
- https://github.com/faker-js/faker/tree/next/src/locales/ru/company

@serembon @salixzs: Are you able to clarify this?

I contacted you as creators of these commits:

- https://github.com/faker-js/faker/commit/cf64d76c757597a3d1efbdc54a269389ecaec8e7
- https://github.com/faker-js/faker/commit/81171c9f9f2e548f9a86eaae3683ead7e28dbd72

**Comment by serembon** [comment]
@ST-DDT hello! [prefix](https://github.com/faker-js/faker/blob/next/src/locales/ru/company/prefix.ts) can only be  `legal_entity_type `

**Comment by ST-DDT** [comment]
> @ST-DDT hello! [prefix](https://github.com/faker-js/faker/blob/next/src/locales/ru/company/prefix.ts?rgh-link-date=2024-06-23T21%3A52%3A17Z) can only be `legal_entity_type `

@serembon Thanks for your fast response. What would you call the suffix in that case?

**Comment by serembon** [comment]
This is part of the company name. It is necessary to save this [name_patterns](https://github.com/faker-js/faker/blob/next/src/locales/ru/company/name_pattern.ts) for generating a name from parts

```
{{company.suffix}}{{company.suffix}}'
{{company.suffix}}{{company.suffix}}{{company.suffix}}
```

If you use only one part, the company name will not be similar to the real one.

**Comment by ST-DDT** [comment]
So the suffix is actually the suffix in this case?

**Comment by serembon** [comment]
> category

Right

**Comment by serembon** [comment]
> So the suffix is actually the suffix in this case?

Right

**Review by ejcheng — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Comment by xDivisionByZerox** [comment]
I just noticed that we missed the update of [`CompanyDefinition`](https://github.com/faker-js/faker/blob/49d7119025d252eecb043647b7d4465352938157/src/definitions/company.ts) in this PR.
@ST-DDT Was this intended, since "suffix" was never part of it in the first place?

**Comment by ST-DDT** [comment]
> @ST-DDT Was this intended, since "suffix" was never part of it in the first place?

It was never part of it in the first place (It is only usd by fake patterns).

**Pull request merged**
