### PR TITLE
infra: relink main to next

### PR DESCRIPTION
**Pull request by Shinigami92**
We renamed the `main` branch to `next`, therefore we now need to _fix_ some links

### CODE REVIEW

**Review by ST-DDT — DISMISSED** [review]

**Comment by xDivisionByZerox** [comment]
Do we need to change the ci trigger here to?
https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/.github/workflows/ci.yml#L3-L7

**Comment by Shinigami92** [comment]
> Do we need to change the ci trigger here to?
> 
> https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/.github/workflows/ci.yml#L3-L7

YES we do! Good catch

**Comment by Shinigami92** [comment]
@ST-DDT 


Looks like you want to discuss again about the (new) schema?
Or in other words: @xDivisionByZerox what is your plan how to structure the new changelog(s)?
_We might want to discuss this in tomorrows meeting_

**Comment by ST-DDT** [comment]
That was not my intention. I cancelled the auto merge and it changed the title back...

**Comment by xDivisionByZerox** [comment]
> YES we do! Good catch

Wasn't entirely sure. That's why I asked^^

> Or in other words: @xDivisionByZerox what is your plan how to structure the new changelog(s)?

I don't see how this is related to this PR, but sure let's discuss it tomorrow (but as stated in Discord I'm really unattached to that topic).

**Review by ejcheng — COMMENTED** [review]
What about the "main" here? Or is this a job name?

https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/.github/workflows/semantic-pull-request.yml#L10-L15

**Comment by Shinigami92** [comment]
> What about the "main" here? Or is this a job name?
> 
> 
> 
> https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/.github/workflows/semantic-pull-request.yml#L10-L15

Yes, that's just a name

**Comment by ejcheng** [comment]
> > What about the "main" here? Or is this a job name?
> > 
> > 
> > 
> > https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/.github/workflows/semantic-pull-request.yml#L10-L15
> 
> Yes, that's just a name

Okay, just checking

**Review by ST-DDT — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]

**Pull request merged**
