### PR TITLE
docs(usage): type definitions aren't strictly necessary

### PR DESCRIPTION
**Pull request by fzn0x**
type definitions aren't strictly necessary here

### CODE REVIEW

**Comment by ST-DDT** [comment]
> type definitions aren't strictly necessary here

They might not be necessary there, but we have them there to reduce the cognitive load from the reader to guess what the method/field is supposed to do/return.

See also:

- https://typescript-eslint.io/rules/explicit-function-return-type/

What is your idea/intention with removing those (aka Why)?

**Comment by fzn0x** [comment]
> > type definitions aren't strictly necessary here
> 
> They might not be necessary there, but we have them there to reduce the cognitive load from the reader to guess what the method/field is supposed to do/return.
> 
> See also:
> 
> * https://typescript-eslint.io/rules/explicit-function-return-type/
> 
> What is your idea/intention with removing those (aka Why)?

Typings still included without specifying `Users`.
Screenshot 2024-04-22 003654

**Comment by fzn0x** [comment]
Improve the example for the Users type definition, or remove it altogether to allow users to explore the usage independently without encountering errors after choosing ESM or CJS.

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
So the issue here is that the example on the readme uses a type that isnt specified anywhere on that page.

**Review by ejcheng — APPROVED** [review]

**Comment by matthewmayer** [comment]
Maybe remove "export" too? If it's just a standalone example.

**Comment by ST-DDT** [comment]
> Maybe remove "export" too? If it's just a standalone example.

I'm undecided on that. Maybe a little bit on the keep it part because I hope this pushes the users to reuse their faker methods and it slightly catches more attention.

**Review by matthewmayer — APPROVED** [review]

**Pull request merged**
