### PR TITLE
fix(helpers): prevent uniqueArray from hanging

### LINKED ISSUE #2207: `County` method used with `uniqueArray` helper crashes faker.
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

Using the `county` method with the `uniqueArray` completely crashes not just faker but my entire runtime. In my case, I discovered it in a React + Storybook project, where I switched from using `country` to using `county`, and my entire browser became unresponsive.

Attached is a stackblitz (based on the one linked in the docs), that does the same thing, comparing the `country` method to the `county` method using the `uniqueArray` helper, where generating some unique countries works fine, but counties do not.

### Minimal reproduction code

https://stackblitz.com/edit/faker-js-demo-rqnnk9?file=index.ts

### Additional Context

I personally use faker in a Vite + Storybook + React environment, using ES Modules targeting an ESNext build. However, it is reproduce-able (as shown in the stackblitz) in plain JS modules.

### Environment Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 63.45 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/22781_1678232715369/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/22781_1678232715369/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 112.0.2
    Safari: 16.3
  npmPackages:
    @faker-js/faker: 8.0.2 => 8.0.2
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

pnpm

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #2207

Adds a max retry logic to uniqueArray.

I chose to use 1000*length rather than a fixed number of retries, as for example if you are 
asking for a length of 2000, then 1000 retries would be insufficient.

This seems sufficient for most sensible use cases.

Obviously uniqueArray has no way to "know" how many unique values the function can return, you could define a function which returns "heads", "tails", but occasionally returns "edge" every 1000000 runs, or if the system date is a Thursday, etc etc.

### CODE REVIEW

**Review by xDivisionByZerox — APPROVED** [review]
The implementation looks good. The failing pipeling seems to be unrelated to your changes. So I already approve 👍

**Comment by matthewmayer** [comment]
> The implementation looks good. The failing pipeling seems to be unrelated to your changes. So I already approve 👍 

Yea that codecov job is quite flaky and seems to fail every so often at random.

**Comment by ST-DDT** [comment]
Instead of reinventing the unique logic, shouldn't we reuse the unique method/logic?

**Comment by matthewmayer** [comment]
> Instead of reinventing the unique logic, shouldn't we reuse the unique method/logic?

I thought that was deprecated?

**Review by Shinigami92 — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]

**Comment by ST-DDT** [comment]
Let's discuss this in the next team meeting.

**Comment by ST-DDT** [comment]
**Team Decision**

We consider this a bandaid fix that solves the issue.
In the future we will reevaluate the entire unique feature again and then also use it consistently in all our unique methods.

**Review by ST-DDT — APPROVED** [review]

**Pull request merged**
