### PR TITLE
fix: fix typescript types for the `unique` method

### PR DESCRIPTION
**Pull request by thefrenchjosh**
The type definitions were missing the rest operator.

### CODE REVIEW

**Review by ST-DDT — COMMENTED** [review]
Your tests look repeated maybe use a for loop?

**Review by Shinigami92 — CHANGES_REQUESTED** [review]
Yeah, something seems odd here :thinking:

**Comment by Shinigami92** [comment]
@thefrenchjosh this now needs a rebase

**Comment by Shinigami92** [comment]
Is this superseded by #456 and can be closed?

**Pull request closed without merging**
