### PR TITLE
fix: adds regex to `random.word` to trim unwanted characters

### PR DESCRIPTION
**Pull request by prisis**

### CODE REVIEW

**Comment by Shinigami92** [comment]
Please fix this in based on the main branch, it has nothing to do with the ts migration 
Also we might want to have a test

**Comment by Shinigami92** [comment]
Also folks could just do it manually filter it in their code for now, so I do not see it that high prio

**Comment by MilosPaunovic** [comment]
> Also folks could just do it manually filter it in their code for now, so I do not see it that high prio

Yeah, but, it's more elegant if we deal with it ourselves in the codebase 🙂 
Anyway, this was one of the opened issues at the original repo, so, someone definitely encountered it.

**Comment by damienwebdev** [comment]
This needs a rebase against main.

**Comment by damienwebdev** [comment]
I'm not sure that I'm confident in this implementation. This seems like we should be modifying the word dictionary of a locale to be more correct for that locale rather than relying on a regex.

**Comment by MilosPaunovic** [comment]
@damienwebdev That approach might be problematic, as words are generated from multiple methods https://github.com/faker-js/faker/blob/a973ee1ce64d2b593f64b633e927382280da8f27/src/random.ts#L169

And some of which, like countries, just have the parenthesis, mostly seen here:
https://github.com/faker-js/faker/blob/main/lib/locales/en/address/country.js

We could go through all the locales, but removing unwanted characters might change meaning of the word or make it incomprehensible.

For the reasons above, my vote goes to the regex approach.

**Pull request closed without merging**
