### PR TITLE
docs: add npm to social links

### PR DESCRIPTION
**Pull request by xDivisionByZerox**
# Description

Add a NPM social icon to the navigation of our documentation page.

image

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
Not sure which social links we need.

**Review by Shinigami92 — APPROVED** [review]

**Comment by xDivisionByZerox** [comment]
> Not sure which social links we need.

You think a user might get overwhelmed by the amount of icons if we would put in all applicable icon?

**Comment by matthewmayer** [comment]
I think that is a concern especially for less well known ones like OpenCollective.

**Comment by matthewmayer** [comment]
I think 6 is tolerable. I would try to avoid 7 or more.

**Pull request merged**
