### PR TITLE
docs: update roadmap for v9

### PR DESCRIPTION
**Pull request by xDivisionByZerox**
# Description

I noticed that the roadmap on our website is pretty outdated. I moved some stuff around and added a section for v9.

Feel free to add topics if you think they should be included in the roadmap.

### CODE REVIEW

**Comment by xDivisionByZerox** [comment]
I just noticed that there is an issue regarding this topic as well.

- #2666

**Review by Shinigami92 — APPROVED** [review]

**Comment by matthewmayer** [comment]
As I mentioned in the linked issue one problem with this is that the roadmap on fakerjs.dev which is what most people will read is linked to v8 not next. It might be good to have the roadmap on the docs site be a stub which links to a single location which we can more easily keep up to date.

**Comment by matthewmayer** [comment]
(Or if not possible, backport the roadmap to v8?)

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
> It might be good to have the roadmap on the docs site be a stub which links to a single location which we can more easily keep up to date.

Yeah, we have to put more thought into that.

> As I mentioned in the linked issue one problem with this is that the roadmap on fakerjs.dev which is what most people will read is linked to v8 not next.

The same applies to stubbing unless we backport the stubbing as well.

For now this improves/fixes the docs, so we should merge and backport this.
But we should discuss a long term solution for this.

**Review by matthewmayer — APPROVED** [review]

**Pull request merged**
