### PR TITLE
refactor(locale): lowercase Mexican color names

### LINKED ISSUE #2841: Check capitisation of ex_MX/color/human
https://github.com/faker-js/faker/blob/9555be88d0a1be312fc4db7e871c8ed1978bac4c/src/locales/es_MX/color/human.ts#L2

              Seems random that some colors are capitalised here?

_Originally posted by @matthewmayer in https://github.com/faker-js/faker/pull/2837#discussion_r1572716818_

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes #2841

- #2841

---

According to chatgpt Spanish color names are spelled using lowercase.
So this PR fixes the Mexican color names.

### CODE REVIEW

**Comment by matthewmayer** [comment]
I'd be happier if we can get some actual Spanish speakers to review. Maybe we can ping some users who contributed to Spanish locale in the past?

**Comment by ST-DDT** [comment]
@rasputino I have seen you have contributed some other Spanish translations as well.
Are you available for a short review of color names?

**Comment by rasputino** [comment]
Sure! I'll take a look at it this weekend.


> @rasputino I have seen you have contributed some other Spanish translations as well.
> Are you available for a short review of color names?

**Comment by ST-DDT** [comment]
Awesome ❤️

**Comment by rasputino** [comment]
@ST-DDT. @matthewmayer 

I'm sorry, but I believe the names are not correct; we shouldn't rely so much on ChatGPT. There are colors like "almendra" ("almond") that simply aren't used or are too "fanciful" to be considered a color.

Also, in Mexico, although there are very few differences and it would be perfectly understood, there are colors that are commonly referred to differently. For example, the color "naranja" (orange) in Mexico would be called "anaranjado." Therefore, IMO, it's not correct to delete the file of colors in Mexican Spanish.

I'm making this proposal to improve and expand the colors in Spanish from Spain (Castilian). For the Mexican version, it should be reviewed by a native from there.

https://github.com/faker-js/faker/commit/7dcac938f047bb09576fcb1f1108c132de51bd24

**Comment by ST-DDT** [comment]
@rasputino Would you like to create a PR or should I merge your commit into this one?

**Comment by rasputino** [comment]
> @rasputino Would you like to create a PR or should I merge your commit into this one?

What do you prefer?

**Comment by ST-DDT** [comment]
Due to maintainer availability and review rules, it will likely be merged faster if you create a new PR.

**Comment by rasputino** [comment]
> Due to maintainer availability and review rules, it will likely be merged faster if you create a new PR.

Created: https://github.com/faker-js/faker/pull/3230

**Comment by ST-DDT** [comment]
@rasputino Just for clarification. Is the Mexican color list

- good enough as is, 
- or should it all be lowercase,
- or should we still remove it to fall back to Spanish?

**Comment by rasputino** [comment]
> @rasputino Just for clarification. Is the Mexican color list
> 
> - good enough as is, 
> - or should it all be lowercase,
> - or should we still remove it to fall back to Spanish?

- It should be in lowercase.


Don’t remove it. It should be reviewed by a Mexican. I can ask some of my Mexican friends if you'd like me to provide the corrections.

**Comment by ST-DDT** [comment]
> I can ask some of my Mexican friends if you'd like me to provide the corrections.

That would be great.

**Comment by ST-DDT** [comment]
@rasputino I updated this PR to switch to lowercase Mexican color names as a basic fix for the reported issue.
If one of your friends could provide a new set of Mexican color names, then I will close this PR in favor of the new additions.

**Pull request merged**
