### PR TITLE
docs(docs/guide): Add typescript support in the guide

### PR DESCRIPTION
**Pull request by ch1lam**

### CODE REVIEW

**Review by Shinigami92 — DISMISSED** [review]

**Comment by Shinigami92** [comment]
A windows user was spotted 👁️

**Review by Shinigami92 — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Comment by ch1lam** [comment]
> A windows user was spotted 👁️

Yes, I'm more used to using windows. This is the problem I found while reading the guide, which is not the same as the [README.md](https://github.com/faker-js/faker/blob/main/README.md). And this is my first PR on github, it might not be standardized enough.😳

**Review by ejcheng — APPROVED** [review]

**Comment by Shinigami92** [comment]
> Yes, I'm more used to using windows. This is the problem I found while reading the guide, which is not the same as the [README.md](https://github.com/faker-js/faker/blob/main/README.md?rgh-link-date=2022-05-12T12%3A17%3A28Z). And this is my first PR on github, it might not be standardized enough.😳

You may want to configure `autocrlf` https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by ch1lam** [comment]
> You may want to configure `autocrlf` https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Oh thanks, this is very useful for me.🙂

**Pull request merged**
