### PR TITLE
chore: add discord link to fakerjs.dev navbar

### PR DESCRIPTION
**Pull request by import-brain**
I think this would help get more people into the Discord server and facilitate a better community.

### CODE REVIEW

**Review by prisis — APPROVED** [review]

**Comment by prisis** [comment]
Just a note, for me it would be a p2-nice-to-have

**Review by Shinigami92 — APPROVED** [review]
For now I think this is okay
But later we may want to embed it into a submenu like in the current Vue docs, or in the next Vitepress seems, there is the possibility to embed an Discord icon next to Twitter and GitHub

See https://staging.vuejs.org/

**Review by ST-DDT — APPROVED** [review]

**Comment by import-brain** [comment]
> For now I think this is okay But later we may want to embed it into a submenu like in the current Vue docs, or in the next Vitepress seems, there is the possibility to embed an Discord icon next to Twitter and GitHub
> 
> See [staging.vuejs.org](https://staging.vuejs.org/)

Yeah, this is okay for now, but we should change it to use icons like the site you linked in the future.

On another note, wow, that site looks amazing!

**Comment by import-brain** [comment]
> For now I think this is okay But later we may want to embed it into a submenu like in the current Vue docs, or in the next Vitepress seems, there is the possibility to embed an Discord icon next to Twitter and GitHub
> 
> See [staging.vuejs.org](https://staging.vuejs.org/)

Yeah, this is okay for now, but we should change it to use icons like the site you linked in the future.

On another note, wow, that site looks amazing!

**Comment by import-brain** [comment]
> For now I think this is okay But later we may want to embed it into a submenu like in the current Vue docs, or in the next Vitepress seems, there is the possibility to embed an Discord icon next to Twitter and GitHub
> 
> See [staging.vuejs.org](https://staging.vuejs.org/)

Yeah, this is okay for now, but we should change it to use icons like the site you linked in the future.

On another note, wow, that site looks amazing!

**Pull request merged**
