### PR TITLE
feat!: another experiment

### PR DESCRIPTION
**Pull request by Shinigami92**
Alternative draft for #1250

This is another solution and would be what was initially planned as second step after #1254

### CODE REVIEW

**Comment by Minozzzi** [comment]
I liked this approach, in my opinion keeps the code separate and organized.

**Comment by Shinigami92** [comment]
Closing these experiments for now

**Comment by ST-DDT** [comment]
@Shinigami92 Do you still need the branch? If not, please delete it.

Commit-ID: c66ddf2659da215f069c7e22592a9d18dcd85f3c

**Comment by Shinigami92** [comment]
Yes, please do not delete them right now so we have a copy and look into it if needed
I just wanted to clean the PR section as we would need to rewrite them anyway as they got to stale

**Pull request closed without merging**
