### PR TITLE
infra(typescript-eslint): switch-exhaustiveness-check

### PR DESCRIPTION
**Pull request by ST-DDT**
Ref: #2508

- #2508

---

Enables the [`@typescript-eslint/switch-exhaustiveness-check`](https://typescript-eslint.io/rules/switch-exhaustiveness-check/) lint rule.

~~This removes default cases that are already covered by the explicit case statements on union types.~~ Delayed to v9.

There are some non-union type switch cases that aren't exhaustive, and won't be detected by typescript-eslint.
I will create a separate issue for that on typescript-eslint's side.

---

Related Issues and PRs:

- https://github.com/typescript-eslint/typescript-eslint/pull/7539
- https://github.com/typescript-eslint/typescript-eslint/issues/2959

### CODE REVIEW

**Review by xDivisionByZerox — DISMISSED** [review]

**Review by matthewmayer — CHANGES_REQUESTED** [review]
Doesn't this change the behavior when called from JavaScript?

**Comment by ST-DDT** [comment]
Yes, it does. Should we delay the default removal to v9? (Although I consider those bad arguments unsupported usage anyway)

**Comment by matthewmayer** [comment]
i support including this in v9.

**Review by matthewmayer — APPROVED** [review]
Looks good without the breaking changes

**Comment by ST-DDT** [comment]
@matthewmayer I reverted the breaking changes for now, so we can enable this rule.
I will create a new PR once the additional options have been added to the rule by typescript-eslint.

**Comment by ST-DDT** [comment]
Created typescript-eslint PR: https://github.com/typescript-eslint/typescript-eslint/pull/7880

- https://github.com/typescript-eslint/typescript-eslint/pull/7880

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
