### PR TITLE
test: use basic reporter

### LINKED ISSUE #1635: Fix `pnpm run test run`
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

`pnpm run test run` fails due to tests timing out.

> test/locale-imports.spec.ts > locale imports > Internal tests to cover `src/locale/*.ts` > should be possible to directly import('../src/locale/af_ZA')
Error: Test timed out in 5000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".

````txt
  ❯ test/locale-imports.spec.ts (232) 41438ms
   ❯ locale imports (232) 41437ms
     ✓ should be possible to directly require('@faker-js/faker/locale/af_ZA')
     ✓ should be possible to directly import('@faker-js/faker/locale/af_ZA') 1009ms
     ❯ Internal tests to cover `src/locale/*.ts` (2) 5035ms
       ✓ should be possible to directly require('../locale/af_ZA')
       × should be possible to directly import('../src/locale/af_ZA') 5027ms
     ✓ should be possible to directly require('@faker-js/faker/locale/ar')
     ✓ should be possible to directly import('@faker-js/faker/locale/ar') 4299ms
     ✓ Internal tests to cover `src/locale/*.ts` (2) 805ms
     ✓ should be possible to directly require('@faker-js/faker/locale/az')
     ✓ should be possible to directly import('@faker-js/faker/locale/az') 387ms
````

### Minimal reproduction code

- `pnpm run test run`

### Additional Context

These two **previously** worked:

- `pnpm run test`
- `pnpm run test run test/locale-imports.spec.ts`

### Environment Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
    Memory: 53.93 GB / 63.69 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (108.0.1462.42)
    Internet Explorer: 11.0.22621.1
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

pnpm

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #1635 

This fixes running tests locally
The previous default reporter cleared the console log everytime when to much is going on in the console
But this results in issues with to many tests and it hangs
So this new reporter do what would be done when `CI=true` would be configured and will not clear the screen anymore
IMO this is even a better UX

### CODE REVIEW

**Comment by ST-DDT** [comment]
I checked locally and the original error is no longer there on my current device.
I will try on my other devices as well later.

**Comment by ST-DDT** [comment]
I tried it on my second device as well as dev containers and am no longer able to reproduce the error described in #1635 .
(Even without the fix described in this PR)

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
It's okay anyway,

**Comment by xDivisionByZerox** [comment]
This is so great! I can finally run tests locally without specifying the test file ♥

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
