### PR TITLE
infra: pnpm removed their strictness

### PR DESCRIPTION
**Pull request by Shinigami92**
pnpm removed their strictness in v9.2 🎉

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]
I haven't tested it outside of corepack.

**Comment by Shinigami92** [comment]
> I haven't tested it outside of corepack.

I already did in node-pg-migrate

**Review by xDivisionByZerox — APPROVED** [review]
For people (like myself) that are not as up to date in the ecosystem discussions: https://github.com/pnpm/pnpm/issues/8087

**Comment by Shinigami92** [comment]
> For people (like myself) that are not as up to date in the ecosystem discussions: https://github.com/pnpm/pnpm/issues/8087

I would like to remember to read the changelog while approving PRs like #2943

- #2943

image

**Comment by matthewmayer** [comment]
> > For people (like myself) that are not as up to date in the ecosystem discussions: https://github.com/pnpm/pnpm/issues/8087
> 
> I would like to remember to read the changelog while approving PRs like #2943
> 
> - #2943
> 
> image

Sounds like a semver-major change to me 😀

**Comment by xDivisionByZerox** [comment]
> > > For people (like myself) that are not as up to date in the ecosystem discussions: [pnpm/pnpm#8087](https://github.com/pnpm/pnpm/issues/8087)
> > 
> > 
> > I would like to remember to read the changelog while approving PRs like #2943 [...]
>
> Sounds like a semver-major change to me 😀

Exactly, the version change log was higly missleading IMO. At the poitn of reading the change, I wasn't aware of that this is a setting we currently use and had forgotten about it as it only pointed ot the "true" case. Sure I could have put some more brain power into it. at the time of approving the original PR, but I do not think that is usually required for minor version updates.

**Comment by Shinigami92** [comment]
Not sure if they are so major strict, but it is also not a breaking change
They just don't throw an error anymore cause so many people complained about their v9.0 decision (I was one of them)

**Comment by matthewmayer** [comment]
image
These two changes seem contradictory in the changelog.

**Comment by ST-DDT** [comment]
Thank you for highlighting the relevant sections of the changelog for the discussion. I was about to ask.

I have read it before approving and multiple times now and I seem to fail to recognise the "major breaking change" part. I dont see any effect this change has on our project except for not requiring the workaround removed in this PR anymore.
I'm not affected by both the original issue and the workaround so I'm not complaining.
Though I admit I missread the linked issue and thought the strict check was added in a minor v9.x instead of v9.0, but since it was removed it doesnt matter either way.

**Pull request merged**
