### PR TITLE
fix(person): Incorrect behavior of name.firstName() function

### LINKED ISSUE #547: Incorrect behavior of `name.firstName()` function
### Describe the bug

When using the faker.name.firstName() function with a non-standard locale and without passing a gender value to the function, the name is still displayed in English.

### Reproduction

For example:
```js
import { faker } from '@faker-js/faker';

faker.locale = 'ru'; // Set another locale

const incorrectFirstName = faker.name.firstName(); // Jack (incorrect)
const correctFirstName = faker.name.firstName(0); // Евгений (correct)
const correctFirstName2 = faker.name.firstName(1); // Жанна (correct)
```

demo: https://stackblitz.com/edit/faker-js-demo-6fb7x2?file=index.ts

### Additional Info

_No response_

### LINKED ISSUE #1553: fullName uses fallback first names in el (Greek)
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

faker.person.fullName() appears to always fall back to English first names, while faker.person.firstName() correctly uses Greek first names.

### Minimal reproduction code

```
faker.setLocale("el");console.log(`First name: ${faker.person.firstName()}, Full name: ${faker.person.fullName()}`)
```

```
Some example outputs:

First name: Άγγελος, Full name: Jerome Βονόρτας
First name: Αναστάσιος, Full name: Gayle Καλύβας
First name: Αντώνης, Full name: Julie Κορνάρος
First name: Αριστείδης, Full name: Nicholas Καλλιγάς IV
First name: Λεωνίδας, Full name: Jenny Δεσποτόπουλος
First name: Μιχαήλ, Full name: Richard Αγγελόπουλος
First name: Μιχαήλ, Full name: Κυρία Kim Αλεξάκης
First name: Σπύρος, Full name: Kellie Παπαδόπουλος I
First name: Στέφανος, Full name: Gladys Βιτάλη
First name: Σωτήριος, Full name: Levi Αυγερινός (επώνυμο)
```

### Additional Context

_No response_

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 42.11 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 98.0
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #547 for az,id_ID, lv, ro, ru, sk, uk locales
fix #1553 for de_AT, nl_BE, en_IN, en_AU and el locales

### CODE REVIEW

**Review by Shinigami92 — DISMISSED** [review]

**Review by ST-DDT — DISMISSED** [review]
It doesnt fix the underlying issue, but IMO it fixes the symptoms so it is good enough.

We have to treat the underlying issue later though (in a new issue if we havent one already).

**Comment by matthewmayer** [comment]
For the four locales de_AT, nl_BE, en_IN and en_AU it was straightforward to split the first_name.ts file into two gendered files. This solves this problem in Faker 7.x:

```
> faker.setLocale("de_AT")
> faker.name.firstName()
'Leandra' //ok, this is from de_AT
> faker.name.firstName("female")
'Brenda' //wrong, this is from en
```

**Comment by matthewmayer** [comment]
For `el`, all the names in first_name.ts were actually male first names! So I made that male_first_name and added some new female_first_names based on popular first names from statistics.gr

```
> faker.setLocale("el")
> faker.person.firstName()
'Διονύσιος'
> faker.person.firstName("female")
'Αννα'
> faker.person.firstName("male")
'Παρασκευάς'
```

**Comment by matthewmayer** [comment]
For the remaining locales the names are either intermingled or I don't know the languages well enough to tell, so this will have to wait until later refactoring:
```
de_CH
es_MX
ge
ko
ne
zh_TW
```

**Review by ST-DDT — DISMISSED** [review]

**Comment by ST-DDT** [comment]
~~Just to be sure, did you only use the mergeArrays function if the "generic" name was exactly the union of "female" and "male"?~~

Nevermind. I checked myself. The files were either missing before or are matching the union.

**Review by ST-DDT — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
