### PR TITLE
refactor(location): deprecate cityName

### LINKED ISSUE #2021: Merge faker.location.city() and faker.location.cityName()
### Clear and concise description of the problem

From just the method names, it is confusing what each method does.

- https://next.fakerjs.dev/api/location.html#city
- https://next.fakerjs.dev/api/location.html#cityname

It also causes issues when a locale does not have a city_name_pattern or city_name locale file.

### Suggested solution

Merge both methods into one. (Not sure about the name yet)

````ts
faker.location.cityName({ allowGenerated: boolean = true });
````

### Alternative

- Rename the methods to account for them generating real and generated city names respectively.

### Additional context

Part of #1346

- #1346

### PR DESCRIPTION
**Pull request by xDivisionByZerox**
Part of #2021.

### CODE REVIEW

**Comment by ST-DDT** [comment]
The other PR https://github.com/faker-js/faker/pull/2051 also adjusts the locale data.

**Comment by xDivisionByZerox** [comment]
> The other PR #2051 also adjusts the locale data.

I know but wanted to prevent merge conflicts as well as breaking changes in THIS PR. I had a really hard time actually finding the deprecation itself in the other PR.

**Comment by matthewmayer** [comment]
Do you plan to make city and cityName return the same data in v8.0? Or you just deprecate cityName in v8.0 and merge the locale data in v9?

**Comment by xDivisionByZerox** [comment]
This is the same as #2051. 
`location.city` already is a superset of `location.cityName`. As described in https://github.com/faker-js/faker/issues/2021#issuecomment-1499260452 we simply deprecate the `*Name` implementation for now. We can think about adding a `generated` option parameter (to only get generated or real cities) in the future if the community requests.

**Review by Shinigami92 — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Pull request merged**
