### PR TITLE
fix: enable algolia search

### PR DESCRIPTION
**Pull request by prisis**
I added the env's into netlify

### CODE REVIEW

**Comment by Shinigami92** [comment]
I cannot review if it's working due to I do not have the API_KEY in my local envs

Can we somehow test this PR with a netlify preview?
Otherwise, did you test it manually?

**Review by griest024 — APPROVED** [review]
code looks fine but I did not acceptance test. Should this close #222 ?

**Comment by prisis** [comment]
Tested it on my local en

https://user-images.githubusercontent.com/2716058/159645920-b5ab888d-5499-49b6-82a8-7e2c0230c10e.mp4

**Review by ST-DDT — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Comment by ST-DDT** [comment]
Works like a charm!

**Pull request merged**
