### PR TITLE
chore(deps): add prettier-plugin-organize-imports

### PR DESCRIPTION
**Pull request by Shinigami92**
Add dev depenedency `prettier-plugin-organize-imports`

This will organize all imports with prettier

I will format all files when some other currently higher prio PRs are merged to reduce merge conflicts

### CODE REVIEW

**Comment by Shinigami92** [comment]
image

lel, ... I think `codecov/patch` is totally useless :rofl: 

Maybe we should just disable it
@ST-DDT any ideas?

**Comment by ST-DDT** [comment]
The issue here is that the imports are considered code, but are never taken into consideration regarding usage.
IMO this is a bug in the code coverage engine that needs fixing. As for us, we could remove this until it is fixed upstream.
We just have to take this into consideration when looking at PRs that add features.

**Comment by Shinigami92** [comment]
@bcoe Do you know anything about this? Is this a bug of c8?

**Review by ST-DDT — APPROVED** [review]

**Comment by bcoe** [comment]
> @bcoe Do you know anything about this? Is this a bug of c8?

My hunch is that it might have to do with how imports are transpiled to JavaScript, vs., an issue with the coverage engine itself. What does the transpiled code look like?

**Review by prisis — APPROVED** [review]

**Pull request merged**
