### PR TITLE
docs: replace deprecated datatype.uuid() with string.uuid()

### PR DESCRIPTION
**Pull request by saranatour1**

### CODE REVIEW

**Review by ST-DDT — DISMISSED** [review]

**Comment by ST-DDT** [comment]
https://github.com/faker-js/faker/blob/next/docs/guide/usage.md also has a few references to the old method.
Would you like to change them in this PR as well?

**Review by xDivisionByZerox — DISMISSED** [review]

**Comment by saranatour1** [comment]
I did that but while I was reading, I noticed that this method has been marked as deprecated as well :
[Link](https://fakerjs.dev/api/helpers.html#unique) , and It was used in the same docs, 
please let me know if I need to close this PR or just submit another one. 
Thanks! 
@ST-DDT

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
> [Link](https://fakerjs.dev/api/helpers.html#unique) , and It was used in the same docs,
> please let me know if I need to close this PR or just submit another one.

helpers.unique is only soft deprecated and there isn't a replacement yet, so there is no need to replace it yet.

**Comment by saranatour1** [comment]
Do I submit another PR?

**Comment by xDivisionByZerox** [comment]
Sorry, I don't understand. Why do you want to open another PR exactly? 🤔

**Comment by saranatour1** [comment]
They Mentioned that there were other changes in another document, I changed them and this is why I am asking.

**Comment by xDivisionByZerox** [comment]
Ah gotcha.  @ST-DDT changed the PR title so it better reflects all changes done in the PR. 
So to conclude: The changes are similar enough that they can be reviewed/merged in the same PR.

Thank you for your contribution ❤️

**Review by matthewmayer — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
