### PR TITLE
feat(#809): add seededRuns to random tests

### PR DESCRIPTION
**Pull request by JVBorges**
- added seededRuns on random modules tests

ref: https://github.com/faker-js/faker/issues/809

### CODE REVIEW

**Review by ST-DDT — CHANGES_REQUESTED** [review]
You might have missunderstood the seesed tests.

1) Seeded test runs are an addition to the existing ones.
2) Seeded test runs follow this pattern:

````ts
expect(actual).toBe(expected)
````

That is equality tests, and no contains checks.

See this test as an example:

https://github.com/faker-js/faker/blob/360bec7c7f3269049eb748523f2d271b6ed36d75/test/address.spec.ts#L109-L110

Please change them to match our other test.

**Comment by JVBorges** [comment]
> You might have missunderstood the seesed tests.
> 
> 1. Seeded test runs are an addition to the existing ones.
> 2. Seeded test runs follow this pattern:
> 
> ```ts
> expect(actual).toBe(expected)
> ```
> 
> That is equality tests, and no contains checks.
> 
> See this test as an example:
> 
> https://github.com/faker-js/faker/blob/360bec7c7f3269049eb748523f2d271b6ed36d75/test/address.spec.ts#L109-L110
> 
> Please change them to match our other test.

Ok, thanks. I'll make the changes.

**Comment by ST-DDT** [comment]
@JVBorges Could you give us a time-frame, for when you are able to update this?

**Comment by JVBorges** [comment]
> @JVBorges Could you give us a time-frame, for when you are able to update this?

Sorry. I'm a little busy right now, so I won't be able to work on it for a long time.

**Comment by ST-DDT** [comment]
No problem. If you don't mind, I'd like to continue with this.

**Comment by JVBorges** [comment]
> No problem. If you don't mind, I'd like to continue with this.

go for it!

**Comment by ST-DDT** [comment]
Superseded by #868

**Pull request closed without merging**
