### PR TITLE
feat(locale): and location to fr_SN

### PR DESCRIPTION
**Pull request by makhtar-sarr**
In this PR I add the most popular cities in Senegal as well as the zip code format.

https://en.wikipedia.org/wiki/List_of_cities_in_Senegal

### CODE REVIEW

**Review by ST-DDT — DISMISSED** [review]

**Review by matthewmayer — COMMENTED** [review]
How about location.state() does it make sense to use the regions for that?

https://en.wikipedia.org/wiki/Subdivisions_of_Senegal?wprov=sfti1#

**Comment by makhtar-sarr** [comment]
Yes, that's a good idea, but should I remove them from the list of cities or not?

**Comment by matthewmayer** [comment]
In other locales where state names happen to duplicate city names, we normally leave them in.

**Review by ST-DDT — APPROVED** [review]

**Review by matthewmayer — APPROVED** [review]
Looks good to me. Location module now seems well covered, could consider adding another PR with improved street names (otherwise will inherit from fr which might not be ideal).

**Comment by ST-DDT** [comment]
Thanks for your contribution ❤️ .

**Pull request merged**
