### PR TITLE
docs: improve finance jsdocs

### PR DESCRIPTION
**Pull request by ST-DDT**
Ref: #203

### CODE REVIEW

**Review by Shinigami92 — APPROVED** [review]

**Comment by Shinigami92** [comment]
https://github.com/bcoe/c8/issues/182

@bcoe @j03m
/cc @antfu 

Did we misc-configured something in our `vite.config.ts`

https://github.com/faker-js/faker/blob/832bf8a2ecaeb83458581212c1c9467575aa3488/vite.config.ts#L1-L14

Or is it really a bug by `c8` that JSDoc multi-line comments are count as _needs to be covered by tests_? :eyes: 
If so, this could be a huge bummer for `vitest` :grimacing:

**Comment by bcoe** [comment]
@Shinigami92 I would take a look at the `.js` generated from the `.ts` file, sometimes there's an unexpected code path that gets generated, by virtue of the structure of the generated code.

**Comment by Shinigami92** [comment]
@bcoe So we already want to switch to just cover the `src` folder instead of the `dist/cjs` (https://github.com/faker-js/faker/pull/432)
Do you think this could already fix it?

**Comment by bcoe** [comment]
> Do you think this could already fix it?

There's a chance. The problem is generally a disconnect between the `.ts` and the `.js`, if the typescript compiler introduces an extra logical expression that's not exercised, or the source map remapping has a hiccup, there might be an uncovered element.

**Review by clarkerican — APPROVED** [review]

**Pull request merged**
