### PR TITLE
chore: remove bower/meteor junk

### PR DESCRIPTION
**Pull request by griest024**

### CODE REVIEW

**Review by clarkerican — APPROVED** [review]

**Review by prisis — APPROVED** [review]

**Comment by damienwebdev** [comment]
I don't think we should remove these. I don't know the bower ecosystem well enough to say whether or not we will break something by doing this. We would need someone from that ecosystem to tell us whether or not we should remove this.

cc: @kkirsche for the last known modifier.

**Comment by griest024** [comment]
I don't know that much about bower either but surely whatever we do to this repo won't affect marak's published packages, right?

**Comment by damienwebdev** [comment]
@griest024 it will not. Maybe v6.0.0 is a breaking release in this regard. We remove a number of older systems that may break if they were to update to v6 for example.

**Comment by Shinigami92** [comment]
https://bower.io/ itself is kinda deprecated and already has a banner on it to migrate to npm and other stuff.

IMO this is safe to be purged, we should just concentrate on npm package
And maybe a CDN version :thinking:

**Comment by griest024** [comment]
Afaik [unpkg](https://unpkg.com/) hosts npm packages automatically.

**Review by damienwebdev — APPROVED** [review]
lgtm

**Pull request merged**
