### PR TITLE
chore(linting): disable `unbound-method` warnings

### PR DESCRIPTION
**Pull request by xDivisionByZerox**
This PR fixes nearly all linter warnings for the [`unbound-method`](https://typescript-eslint.io/rules/unbound-method/) rule.

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]

**Review by import-brain — DISMISSED** [review]

**Comment by ST-DDT** [comment]
> I could call them in an anonym function as well but that would instantiate a new `Fake` or `Unique` every function call and I'm not happy with that.

I currently see two ways for this:
- convert them to standalone functions
- use a private method to initialize the module instance and return the anonymous function call.

**Comment by Shinigami92** [comment]
> > I could call them in an anonym function as well but that would instantiate a new `Fake` or `Unique` every function call and I'm not happy with that.
> 
> I currently see two ways for this:
> 
> * convert them to standalone functions
> * use a private method to initialize the module instance and return the anonymous function to initialize the field with.

What is the general problem with how it currently works in main branch?
We already hacked it with the implementation in all the constructors using:

```ts
// Bind `this` so namespaced is working correctly
for (const name of Object.getOwnPropertyNames(<Module>.prototype)) {
  if (name === 'constructor' || typeof this[name] !== 'function') {
    continue;
  }
  this[name] = this[name].bind(this);
}
```

So if this PR just aims to get rid of the warning, we might just want to turn the warning off and don't care
Please also note that folks in real world already uses code like
```ts
import { faker } from '@faker-js/faker'

const uuid = faker.datatype.uuid

const id = uuid()
```
and until now, we support this
_even if I don't like our current hack, _ but the only way to really fix that, would be to rewrite EVERYTHING back to composable functions like

```ts
function datatype(faker = faker() /* or = new Faker() ?! */ ) {
    uuid() {
        return ... using something with faker. ....
    }
}
```

This would be a complete breaking change and currently I don't see that (at least not before we tackled more important parts like outsource locales / maybe using a monorepo)

**Comment by xDivisionByZerox** [comment]
> So if this PR just aims to get rid of the warning, we might just want to turn the warning off and don't care

So I'm reverting all changes and changing the linter config instead?  Just give me a thumbs up or down and I will act accordingly. My only plan was to get rid of the warnings since they are triggering my OCD during development.

**Comment by ST-DDT** [comment]
I'm fine either way, but the warnings bother me as well. Maybe put this on our agenda for tomorrow.

**Comment by xDivisionByZerox** [comment]
Decision from todays meeting:
Remove the linter rule and revert the changes done in this PR. Explanation can be found in [Shinigami's comment](https://github.com/faker-js/faker/pull/1128#issuecomment-1174712194).

**Comment by Shinigami92** [comment]
> I didn't close this PR :/ if you drop all changes you made, does it auto-close?

Never heard of this behavior, in the log history of GitHub it says you closed it.

**Comment by Shinigami92** [comment]
> I know, but I promise I didn't click the close button. Since we decided to not "fix" these warnings I first wanted to revert all commits I did and then just thought. Fk it, I'll rebase and drop all commits (basically resetting). After force pushing "the changes" I received a notification that I closed the PR ¯\\_(ツ)_/¯

RIP

**Review by Shinigami92 — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Pull request merged**
