### PR TITLE
ci: allow all commit keywords in PR titles and add locale keyword

### PR DESCRIPTION
**Pull request by ST-DDT**
Currently we cannot use `locale` commit keywords, however some of our PRs contain that.
We even have a tag for that.
It would be nice if we could highlight these PRs in changelogs/release notes, so the user can quickly either search for them or mentally discard them.

Recommended usage: `locale(pl): add/update xyz`

### CODE REVIEW

**Comment by Shinigami92** [comment]
We need to investigate why only these types are allowed, maybe the configuration in our project is wrong?
image

**Review by pkuczynski — DISMISSED** [review]

**Comment by pkuczynski** [comment]
Great idea!

**Comment by ST-DDT** [comment]
We can only use `workflow` after this PR is merged.

**Comment by Shinigami92** [comment]
> We can only use `workflow` after this PR is merged.

Why that? Did you see my comment above?

**Comment by ST-DDT** [comment]
It is part of our commit keywords and after this PR is merged, it is also part of the config.

**Comment by Shinigami92** [comment]
But this PR is about `locale` and not `workflow`
I assume the whole config is not taken at all! And it falls back to the default config.

**Comment by ST-DDT** [comment]
I renamed the title. Is it better now?

**Comment by Shinigami92** [comment]
> I renamed the title. Is it better now?

Oh nonono 😱, I highly assume you totally misunderstood me
I can explain you via voice chat tomorrow if you like to

**Review by Shinigami92 — APPROVED** [review]
Oh fucking hell whats up with my GitHub?!?!?!! There are cache issues! You already changed the files 👀 
I needed to retrigger several times a hard reload and now I see that you already commited it, I'm sorry

**Review by import-brain — APPROVED** [review]

**Pull request merged**
