### PR TITLE
fix(person): delete set of invalid names in en_NG

### PR DESCRIPTION
**Pull request by nbroad1881**
These names don't seem legitimate

### CODE REVIEW

**Comment by matthewmayer** [comment]
It seems these may be literal translations of Nigerian names in other languages eg  eg Daluchi in Igbo 

https://www.legit.ng/ask-legit/quotes-messages/1501704-powerful-nigerian-names-meanings-fascinate-you/  but I couldn't find much evidence people use these translations in English.

**Review by xDivisionByZerox — APPROVED** [review]
Works for me.

**Comment by matthewmayer** [comment]
Hmm at some point this was a different list with fewer traditional English names

https://github.com/faker-js/faker/blob/7dc1bc0609b7d7865835cabed86c30e239c357c8/lib/locales/en_NG/name/male_first_name.js

**Review by ST-DDT — APPROVED** [review]

**Comment by matthewmayer** [comment]
OK i found the original commit:

https://github.com/faker-js/faker/commit/fb62766421f77c1978b8dbc6a4d26778953382da

@prinx if you are still around maybe you can help verify this.

**Comment by ST-DDT** [comment]
> Hmm at some point this was a different list with fewer traditional English names
> 
> https://github.com/faker-js/faker/blob/7dc1bc0609b7d7865835cabed86c30e239c357c8/lib/locales/en_NG/name/male_first_name.js

If you look those up please also include the commit id that added/removed the other data.

Then I can try to lookup the original PR that changed these.

If @nbroad1881 confirms that the other names are fine/used in en_ng, then we can merge this.

**Comment by ST-DDT** [comment]
> OK i found the original commit:
> 
> [fb62766](https://github.com/faker-js/faker/commit/fb62766421f77c1978b8dbc6a4d26778953382da)

Merged in https://github.com/faker-js/faker/commit/f694a2e9e717ae040678eb81bdd7b80e0c95f826

<details>
<summary>Original PR discussion (as far as recoverable):</summary>

Author | Time | Comment
-- | -- | --
prinx | 2021-03-09 05:46:27 | ``While testing I ran the the `browser` script, which overwrote the files in the `examples` and `dist` folders.``
Marak | 2021-03-09 14:05:00 | ``We can't accept pull requests that modify `/dist` or `examples` ``
prinx | 2021-03-09 14:22:51 | ``Yes, I was wondering. Thanks. will revert the changes and create a PR``
prinx | 2021-03-10 22:37:34 | ``Hi @Marak . FYI.``
Marak | 2021-03-11 15:20:21 | ``While testing I ran the the `browser` script, which overwrote the files in the `examples` and `dist` folders.``
Marak | 2021-03-11 15:20:30 | ``Thank you for your contributions @prinx   Merged!``
prinx | 2021-03-11 17:11:12 | ``You are welcome @Marak . Thanks for merging too. Hoping to contribute more.``

No more (recoverable) contributions or comments to FakerJs by prinx after that.

</details>

**Comment by prinx** [comment]
> OK i found the original commit:
> 
> [fb62766](https://github.com/faker-js/faker/commit/fb62766421f77c1978b8dbc6a4d26778953382da)
> 
> @prinx if you are still around maybe you can help verify this.

Yes, those names are literal translations of local names to English but are not used in English as stated. They can be removed. Thanks for spotting that.

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
