### PR TITLE
feat(locale): add Dutch province abbreviations

### PR DESCRIPTION
**Pull request by RobinvanderVliet**
According to: https://en.wikipedia.org/wiki/ISO_3166-2:NL

### CODE REVIEW

**Review by xDivisionByZerox — DISMISSED** [review]
While I already approve, it would be nice if you could already sort the values alphabetically (a-z). We plan on 
enforcing this via the locale generation script in the future. So if you could already do this we could reduce the git diff in the future :)

**Comment by RobinvanderVliet** [comment]
> While I already approve, it would be nice if you could already sort the values alphabetically (a-z). We plan on enforcing this via the locale generation script in the future. So if you could already do this we could reduce the git diff in the future :)

I intentionally kept them in the same order as [state.ts](https://github.com/faker-js/faker/blob/next/src/locales/nl/location/state.ts), because I thought the two files were connected in some way.

If that is not needed, I can order them alphabetically.

**Comment by ST-DDT** [comment]
> I intentionally kept them in the same order as [state.ts](https://github.com/faker-js/faker/blob/next/src/locales/nl/location/state.ts), because I thought the two files were connected in some way.
> 
> If that is not needed, I can order them alphabetically.

No, the files aren't connected with each other, so please sort this one alphabetically.
We keep connected data in the same file so they can be changed in one step and dont risk them diverging from each other. See also our airline.airline data.

**Comment by RobinvanderVliet** [comment]
I sorted them in this pull request and also in #2233.

**Review by xDivisionByZerox — APPROVED** [review]

**Comment by matthewmayer** [comment]
@RobinvanderVliet don't worry about merging next into your PR branches, this will be done automatically before the feature is squash merged. You only need to bother if there are conflicts.

**Review by ejcheng — APPROVED** [review]

**Review by matthewmayer — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Pull request merged**
