### PR TITLE
refactor(location)!: rename definition city to city_pattern

### LINKED ISSUE #2021: Merge faker.location.city() and faker.location.cityName()
### Clear and concise description of the problem

From just the method names, it is confusing what each method does.

- https://next.fakerjs.dev/api/location.html#city
- https://next.fakerjs.dev/api/location.html#cityname

It also causes issues when a locale does not have a city_name_pattern or city_name locale file.

### Suggested solution

Merge both methods into one. (Not sure about the name yet)

````ts
faker.location.cityName({ allowGenerated: boolean = true });
````

### Alternative

- Rename the methods to account for them generating real and generated city names respectively.

### Additional context

Part of #1346

- #1346

### PR DESCRIPTION
**Pull request by xDivisionByZerox**
Fixes #2021, #1471.

### CODE REVIEW

**Review by Shinigami92 — APPROVED** [review]

**Comment by matthewmayer** [comment]
this doesn't actually fix #2021 though right? Because the two methods still return different data.

**Comment by Shinigami92** [comment]
> this doesn't actually fix https://github.com/faker-js/faker/issues/2021 though right? Because the two methods still return different data.

- https://github.com/faker-js/faker/issues/2021#issuecomment-1499260452

> We will start without a generated/fictional parameter and will add that back when users request them. (This avoids breaking the API when removing the parameter if unneeded)

**Comment by matthewmayer** [comment]
But i mean even after this PR is merged, say

`fakerEN.location.city()` and `fakerEN.location.cityName()`
`fakerDE.location.city()` and `fakerDE.location.cityName()`

do not behave the same, so there would need to be another PR before https://github.com/faker-js/faker/issues/2021 is considered fixed?

**Comment by xDivisionByZerox** [comment]
> But i mean even after this PR is merged, say
> 
> `fakerEN.location.city()` and `fakerEN.location.cityName()` `fakerDE.location.city()` and `fakerDE.location.cityName()`
> 
> do not behave the same, so there would need to be another PR before #2021 is considered fixed?

No, because `location.city()` already returns a superset of `location.cityName()`. 
I have explained this to you this in https://github.com/faker-js/faker/pull/2070#issuecomment-1514920745

**Comment by matthewmayer** [comment]
ok then maybe #2021 should be renamed? Because the methods are not being merged.

**Comment by matthewmayer** [comment]
in what way does location.city()  return a superset of location.cityName()?

fakerDE.location.cityName() can return Düsseldorf but fakerDE.location.city() will never return Düsseldorf

**Comment by xDivisionByZerox** [comment]
> in what way does location.city() return a superset of location.cityName()?
> 
> fakerDE.location.cityName() can return Düsseldorf but fakerDE.location.city() will never return Düsseldorf

In that case, that's an issue with the `fakerDE` instance. Not the method implementation.

**Comment by matthewmayer** [comment]
Right so these locales will need fixing in a seperate PR if we want city() to also return their real city names

[
'de',    'dv',    'en',
    'en_CA', 'it',    'ka_GE',
    'ko',    'nb_NO', 'ne',
    'ro',    'tr',    'uk',
    'ur'
]

**Comment by xDivisionByZerox** [comment]
The following locales are in fact able to return real city names:
- [dv](https://github.com/faker-js/faker/blob/4d0458c96071917c8c3bb85fa61544caf8ff1763/src/locales/dv/location/city.ts#L7)
- [en](https://github.com/faker-js/faker/blob/4d0458c96071917c8c3bb85fa61544caf8ff1763/src/locales/en/location/city.ts#L6)
- [ne](https://github.com/faker-js/faker/blob/4d0458c96071917c8c3bb85fa61544caf8ff1763/src/locales/ne/location/city.ts#L6)
- [ro](https://github.com/faker-js/faker/blob/4d0458c96071917c8c3bb85fa61544caf8ff1763/src/locales/ro/location/city.ts#L6)
- [tr](https://github.com/faker-js/faker/blob/4d0458c96071917c8c3bb85fa61544caf8ff1763/src/locales/tr/location/city.ts#L6)
- [uk](https://github.com/faker-js/faker/blob/4d0458c96071917c8c3bb85fa61544caf8ff1763/src/locales/uk/location/city.ts#L2)

**Review by ST-DDT — APPROVED** [review]

**Pull request merged**
