### PR TITLE
refactor(locale): modernise buzz- and catch-phrases

### LINKED ISSUE #2929: Modernise buzz- and catch-phrases
Extracted from discussion at https://github.com/faker-js/faker/pull/2921#discussion_r1616518906

Some of the phrases in company/buzz_adjective etc feel quite dated, using early 2000s Web 2.0/dot-com bubble language. 

Some outdated phrases could be removed and replaced with more modern phrases.

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #2929

### CODE REVIEW

**Comment by ST-DDT** [comment]
Lools good to me maybe throw these also in there:
- solar powered
- heat pump
- cloud
- cloud driven
- secure
- relyable
- scaleable
- redundant
- powerful
- consumer-driven
- autonomous
- self learning
- smart home device

**Comment by ST-DDT** [comment]
Maybe ask an LLM for more modern buzz words.

**Comment by ShaharIlany** [comment]
> Maybe ask an LLM for more modern buzz words.

From ChatGPT:

Innovative
Hyper-scalable
Agile
Dynamic
Sustainable
Visionary
Seamless
AI-powered
Data-driven
Cloud-native
Scalable

**Comment by matthewmayer** [comment]
I did already use ChatGPT to help identify which words sounded most outdated and propose a few more. 

I'll try to top up with some additional ones so the overall number of words stays roughly the same.

**Comment by ST-DDT** [comment]
@matthewmayer Could you please complete this PR?

**Comment by matthewmayer** [comment]
im actually fairly happy with current state of the PR. Don't want to add it too many words at the moment, because its not always clear which new words will actually stand the test of time, and which will become quickly dated. Focus is mostly on removing the very outdated terms, and i think there's still plenty of remaining definitions that we dont need to add too many.

**Review by ST-DDT — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
