### PR TITLE
refactor(datatype): standardize arguments

### LINKED ISSUE #1349: Standardize function parameters and defaults
### Clear and concise description of the problem

Most methods have various ways to specify parameters and have different defaults.

### Suggested solution

All methods should be checked that they have:
- consistent parameter definitions
- consistent parameter names
- consistent parameter defaults

The consistency should span across all modules.

### Alternative

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xDivisionByZerox**
Part of #1349.

Standardize all function signatures in the `DatatypeModule` to support an options object.

### CODE REVIEW

**Comment by xDivisionByZerox** [comment]
Should this allow for a `number`  argument?
https://github.com/faker-js/faker/blob/de7ed2e3b823131345995da6ec52c2b0c40c8d6e/src/modules/datatype/index.ts#L327

**Comment by xDivisionByZerox** [comment]
> Please run pnpm run `generate:locales`, `pnpm run generate:api-docs`, and `pnpm run test -u` to generate/update the related files,

I did all of them and no other files where generated 🤔

**Comment by Shinigami92** [comment]
I manually removed `test/scripts/apidoc/temp/` and then run `pnpm run test -u`
Then the snapshots generated newly :shrug: 

/ping @ST-DDT

**Comment by ST-DDT** [comment]
> I did all of them and no other files where generated 🤔

Worked for me without issues.

**Review by ST-DDT — APPROVED** [review]

**Comment by xDivisionByZerox** [comment]
> > I did all of them and no other files where generated 🤔
> 
> Worked for me without issues.

I work on a windows machine. Might that be a problem somehow? Just the only thing that comes to mind right now...

**Comment by ST-DDT** [comment]
> I work on a windows machine.

I as well. Did you run `pnpm run build` before running `pnpm run test -u`?

**Comment by xDivisionByZerox** [comment]
> I as well. Did you run `pnpm run build` before running `pnpm run test -u`?

No, I didn't 🤔
Why would that be required to update the snapshots? Vitest is run against the typescript source, no?

But thanks for the info, I'll do that next time.

**Comment by matthewmayer** [comment]
seems weird to change the signature when the method is already deprecated in this version. If you are currently using 

`faker.datatype.string(42)` we want you to change to `faker.string.sample({length:42})` rather than `faker.datatype.string({length:42})` no?

**Comment by xDivisionByZerox** [comment]
> seems weird to change the signature when the method is already deprecated in this version. If you are currently using
> 
> `faker.datatype.string(42)` we want you to change to `faker.string.sample({length:42})` rather than `faker.datatype.string({length:42})` no?

Due to #1349, `faker.string.*` will be standardized as well in a later PR as well. I'm currently scoping related PR per module (for reviewing reasons).

**Review by Shinigami92 — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]

**Pull request merged**
