### PR TITLE
docs: override default vitepress brand colors

### LINKED ISSUE #2626: Title and buttons on homepage have gone blue?
Has some CSS gone astray? Title is now blue and the Browse API button is quite hard to read.

https://fakerjs.dev/

Screenshot 2024-01-28 at 20 21 45

https://web.archive.org/web/20231129222728/https://fakerjs.dev/

Screenshot 2024-01-28 at 20 21 36

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #2626

Originally I was going to make it green but i think red looks quite nice (took the hue from the Faker logo, the saturation and lightness values are from the default Vitepress theme).

Screenshot 2024-01-29 at 07 40 46

Screenshot 2024-01-29 at 07 40 50

Screenshot 2024-01-29 at 07 41 02
()
Screenshot 2024-01-29 at 07 40 57

### CODE REVIEW

**Review by ST-DDT — COMMENTED** [review]
The faker title looks  quite pink on the dark background, and the difference to the button is very visible.

grafik

**Comment by matthewmayer** [comment]
I think maybe decide first in the meeting if you prefer red green or blue in general, and then I can tweak the colours to make it look nice everywhere.

**Comment by ST-DDT** [comment]
**Team Decision**

- We decided to stick to the green design for now.
- We can rethink our "corporate"/brand design later, currently we are too busy for that and it needs to be done for more than the website.

**Comment by matthewmayer** [comment]
Back to a green design similar to the old theme

Screenshot 2024-02-04 at 14 39 02
Screenshot 2024-02-04 at 14 38 58

**Review by Shinigami92 — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Pull request merged**
