### PR TITLE
feat(domain_suffix): add missing domain for id_ID

### PR DESCRIPTION
**Pull request by fzn0x**
add `id` as one of all domain_suffix

https://en.wikipedia.org/wiki/.id

### CODE REVIEW

**Review by MilosPaunovic — APPROVED** [review]

**Comment by prisis** [comment]
Didn't check before, can you add a test if its possible

**Comment by fncolon** [comment]
Will work on this sunday!

**Comment by fncolon** [comment]
> Didn't check before, can you add a test if its possible

Since there is no system logic and algorithm changes, what i see is we didn't need unit tests, correct me if I'm wrong, thank you!

**Review by Shinigami92 — APPROVED** [review]

**Review by damienwebdev — APPROVED** [review]
lgtm

**Comment by fncolon** [comment]
Thanks to make clear the commit name!

**Pull request merged**
