### PR TITLE
chore(release): 7.5.0

### PR DESCRIPTION
**Pull request by Shinigami92**

### CODE REVIEW

**Review by xDivisionByZerox — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Comment by xDivisionByZerox** [comment]
But why do you have all these version changes in the package.json file? This should be done y renovate, shouldn't it?

**Comment by Shinigami92** [comment]
> But why do you have all these version changes in the package.json file? This should be done y renovate, shouldn't it?

Because otherwise while in the release process the pnpm lock file will be regenerated and then it cannot commit it while in release process and then fail

Some of these are also even explicitly omitted by our renovate config (I think)

**Comment by Shinigami92** [comment]
So no, the ignores are not in there anymore
I don't know why tsx doesn't got updated, but I think the node types are somehow really special

**Comment by 1LISA2** [comment]
images (3)
下载 (4)

**Pull request merged**
