### PR TITLE
docs: add banner to v7 docs

### LINKED ISSUE #1497: Banner doesn't show on https://v6.fakerjs.dev/ and https://v7.fakerjs.dev/
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

it looks like https://github.com/faker-js/faker/pull/1487 was supposed to show a banner "These docs are of an old version" on https://v6.fakerjs.dev/ however no banner is shown. Does this need to be backported?

### Minimal reproduction code

_No response_

### Additional Context

_No response_

### Environment Info

```shell
n/a
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #1497 backport  #1487 Note this PR is against the v7 branch

### CODE REVIEW

**Comment by ST-DDT** [comment]
Maybe we should bump all doc dependencies to latest/the same as next.
And maybe also use the latest docs scripts.
(But I can that in a separate PR as well)

**Comment by matthewmayer** [comment]
i tried to just make the minimal set of changes to get it to work

**Review by ST-DDT — CHANGES_REQUESTED** [review]
For me the banner is displayed behind the top-bar:

grafik

I adjusted the css to increase visibility:

grafik

I'm using FF.

**Comment by matthewmayer** [comment]
Does that happen for you just on v7 or also next?

**Comment by ST-DDT** [comment]
> Does that happen for you just on v7 or also next?

I only checked this PR. I haven't observed this on next yet. IIRC the banner support was added by a new version of vitepress.

**Comment by matthewmayer** [comment]
Hmm yes now E2E test is failing because banner covers the menu bar. Perhaps its necessary to upgrade to the newer version of vitepress with proper banner support.

image

**Comment by matthewmayer** [comment]
outdated, closing

**Pull request closed without merging**
