### PR TITLE
<?>: split download size in half

### PR DESCRIPTION
**Pull request by Shinigami92**
**EXPERIMENTAL**

### What is this?:

1. All TS files in `src/locales` were converted into `.json` files
2. These are then bundled together as `src/locales/<locale>.json` file to require/import them (for at-dev time)
3. They are copied into `dist/locales/<locale>.json` and are required/imported by cjs and esm from same source (for at-bundled time)

### Open TODOs:

- fix tests
- manage generated docs
- fix bugs (specially locale `ar` and `ur`)

### Later?

- write a locale validator
- write a locale analyser to get how many % is missing for a locale

To review this PR, I tried as best as I could to separate all commits

### CODE REVIEW

**Comment by pkuczynski** [comment]
Just out of the interest: what's the benefit of having locales as json vs ts?

**Comment by Shinigami92** [comment]
> Just out of the interest: what's the benefit of having locales as json vs ts?

Most important one: splitting the package size into HALF!

Second important one: having simpler files to manage
like reducing all the boiler plate around the real content
and making it somewhat simpler for a contributor to contribute

**Comment by Shinigami92** [comment]
Closing these experiments for now

**Comment by ST-DDT** [comment]
@Shinigami92 Do you still need the branch? If not, please delete it.

Commit-ID: 4203c3d8dfea49f7bb414a7e2ed68d9681aac71d

**Comment by Shinigami92** [comment]
Yes, please do not delete them right now so we have a copy and look into it if needed
I just wanted to clean the PR section as we would need to rewrite them anyway as they got to stale

**Pull request closed without merging**
