### PR TITLE
chore: support dark mode for favicon

### PR DESCRIPTION
**Pull request by antfu**
Before / After
image

### CODE REVIEW

**Comment by Shinigami92** [comment]
@antfu OH MY GOOD
Welcome :heart:

**Review by Shinigami92 — APPROVED** [review]

**Comment by Shinigami92** [comment]
Please not that we internally will also have a new logo. (#101)
But in the meantime, this is a welcome change :slightly_smiling_face:

**Review by MilosPaunovic — APPROVED** [review]

**Review by prisis — APPROVED** [review]

**Comment by JessicaSachs** [comment]
Yes! I'm working on the magic panda. Welcome! 👋

**Comment by poyea** [comment]
Do we need a dark mode (perhaps a toggle) for the whole doc?

**Comment by Shinigami92** [comment]
> Do we need a dark mode (perhaps a toggle) for the whole doc?

I want that! Please create an issue for that.

**Pull request merged**
