### PR TITLE
chore: add Module suffix to module classes

### PR DESCRIPTION
**Pull request by Shinigami92**
Referencing: #778 and #751

- Re-structure / moving of modules will be done later
- Exporting modules as type can be done in a separate PR to preserve commit message history / changelog

### CODE REVIEW

**Review by ST-DDT — CHANGES_REQUESTED** [review]
This breaks our docs generation.

**New**

grafik

All class modules are missing.

**Review by ST-DDT — APPROVED** [review]

**Review by pkuczynski — CHANGES_REQUESTED** [review]
Hmm, what's the point of this change? I see no value in calling every class a module and it is confusing with es6 modules...

**Comment by Shinigami92** [comment]
> Hmm, what's the point of this change? I see no value in calling every class a module and it is confusing with es6 modules...

It hasn't anything to do with es6
We already named them modules everywhere, in docs, in discussions, when we are talking about them, in unit tests, etc...

We have an issue requesting for exporting the `_Date` module as type #778 and we discussed there to first rename all the modules with that prefix to be
1. consistent
2. prevent conflicts with e.g. js `Date`
3. We decided against to name them e.g. `FakerDate`, because this could come into confusion with that it e.g. wrappes the `Date` which is not the case.

**Comment by ST-DDT** [comment]
I have to agree with @Shinigami92 here.
In my mind, these are our modules.
Unless you have a better suggestion on how to name these, I'm in favor of merging this.

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
IMO there is no need to explicitly call the modules `XyzModule`.
How about naming the modules `XyzFaker`. That way its obvious, that it's a faker module and not a datatype.

e.g.
- DateFaker
- NumberFaker
- StringFaker
- FinanceFaker
- MusicFaker
- VehicleFaker
- ....

Later on, if we actually manage to tree-shake them, then its probably easier to use a `DateFaker` than a `DateModule`.

**Comment by pkuczynski** [comment]
> IMO there is no need to explicitly call the modules `XyzModule`. How about naming the modules `XyzFaker`. That way its obvious, that it's a faker module and not a datatype.

This makes much more sense to me and less chance to conflict with some other package also exporting `DateModule`. The only difference to @ST-DDT proposal, I would rather call them `FakerDate`, then `DateFaker`.

Saying all of that I am stil wondering if use case presented in #778 is a valid one. We use classes construct for namespacing only. They don't create real objects in a sense, that there is no `new FakerDate()`. @JontyMC should be rather passing whole faker instance to his _test data builder_, which would be more syntactically correct, but also more readable:

```
date?: (faker: Faker) => Date;
```

**Comment by Shinigami92** [comment]
Since I totally disagree with the suggestions, I'm closing this PR from my side as I don't want to be associated with the commit history. You are free to make the changes yourself.  I've given several reasons why it's a bad idea to name it something else.

**Comment by Shinigami92** [comment]
So just to summarise up why I only see that it can be named `*Module`:

- All of [#816 pr-description](https://github.com/faker-js/faker/pull/816#issue-1197468027)
- All of [#816 comment(1094238003)](https://github.com/faker-js/faker/pull/816#issuecomment-1094238003)
- The fact that we are calling them this way when talking to each other everywhere
- The fact that we have currently 50x the naming `module` in JSDoc comments and even variable names already in our codebase (`src/`)
- The fact that a user can be confused about that e.g. `FakerDate` is a wrapper around `Date`.
- `DateFaker` is not really well, because I would assume that if I have e.g. `(faker: Faker) => ...` I can call it with `(faker.date)`, which is NOT the case! It is not an abstraction or interface but just a module inside Faker.
- I even want to move code out of `FakeModule` (_fake not faker!_), because I would like to prevent "naming collision" while using autocomplete, as same as with `database` vs `datatype`. For more see: https://github.com/faker-js/faker/discussions/805

And most hilariously, the issue author could just use `(dateModule: typeof faker.date) => ...` or `(dateModule: Faker['date'])` and archive exactly what they want, today.

**Comment by JontyMC** [comment]
I changed the design of our test data builders after the previous conversation because I realised it was over complicating things, so we no longer need to explicitly import the Date module.

However, I still think the API of faker would benefit from explicit typings. I outlined this before, but the Date module is part of the external facing API. There is no way to hide this. Eg, if you right click > goto definition on faker.date in vs code, it will take you to that type (currently _Date). It will also happily import the type for you and blow up at runtime, which is really why I raised the bug in the first place to help others who might do the same thing (probably unlikely...).

I didn't know you could do either of typeof faker.date or Faker['date'], so I appreciate the learning. However, all this is actually doing here is aliasing the underlying _Date class.

IMO, given it is impossible to hide the type of the modules, it would be nicer for documentation purposes if it were a type or interface and named consistently. Whether this is a class or whatever behinds the scenes is then actually an implementation detail. And for what its worth, I think xxxFaker is the least bad naming convention. You can still call them modules, just the xxxFaker module.

**Pull request closed without merging**
