### PR TITLE
chore(deps): update pnpm-lock

### PR DESCRIPTION
**Pull request by ST-DDT**
This PR hopefully fixes the irrelevant warning during push:
https://github.com/faker-js/faker/security/dependabot/16

````diff
- vite: 5.0.11(@types/node@20.11.6)
+ vite: 5.0.12(@types/node@20.11.6)
````

For the future we should let renovate do this, but I just want the warning gone.

### CODE REVIEW

**Review by xDivisionByZerox — APPROVED** [review]
> For the future we should let renovate do this, but I just want the warning gone.

Isn't u/dependabot the bot that usually creates security auto fix PR's?

**Comment by ST-DDT** [comment]
grafik

I'm not sure why exactly but this is either because it is not a direct dependency, or because we have at least two major versions of that dependency in the lock file.

**Comment by Shinigami92** [comment]
> grafik
> 
> 
> 
> I'm not sure why exactly but this is either because it is not a direct dependency, or because we have at least two major versions of that dependency in the lock file.

That could be right 🤔
We definitely have one from Vitest and one from VitePress

Normally in that case de-duplication takes place if possible.
I cannot look right now into the change because of mobile screen

---

Edit:

We do have v5 and v4 in our dependency-tree. I'm not totally sure what you are referring to now. Maybe lets talk later on Discord to show and clarify what the problems are.

**Comment by ST-DDT** [comment]
> I'm not totally sure what you are referring to now. Maybe lets talk later on Discord to show and clarify what the problems are.

The issue is that dependabot does not create a fix PR itself and I had to do that myself.

There is no problem with this PR itself.

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
