### PR TITLE
refactor(vehicle): add more non-US vehicle manufacturers

### LINKED ISSUE #2881: Vehicle data is very US-centric
i noticed in #2874 that the vehicle data is heavily US-centric, mostly featuring US manufacturers and US models, whereas the generic en locale is supposed to cover all English-speaking regions. Once #2874 is merged i can follow up with a new PR to add some more popular missing brands popular in US, UK, India e.g.

* Subaru
* Mitsubishi
* Peugeot
* Citroën
* Suzuki
* Renault

Plus some EV manufacturers like 
* BYD
* NIO
* Rivian

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #2881

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Comment by xDivisionByZerox** [comment]
Is this a `refactor` or a `feat`? I lean more towards `refactor` but want to hear your oppions.

**Comment by matthewmayer** [comment]
I'm never sure what to pick when I'm just adding data without making any code changes. Maybe we need a new commit type for that.

**Comment by ST-DDT** [comment]
It is a locale PR. So I would love a `locale(module):` nomenclature. Until then it is I'm fine with either of those.

**Comment by xDivisionByZerox** [comment]
> It is a locale PR. So I would love a `locale(module):` nomenclature. Until then it is I'm fine with either of those.

But there is a difference when I add completely new locale data (`feat(locale)`) or if I change (this includes additions) existing ones (`refactor(locale)`). :thinking:

**Comment by ST-DDT** [comment]
> But there is a difference when I add completely new locale data (`feat(locale)`) or if I change (this includes additions) existing ones (`refactor(locale)`). 🤔

For the user of the new version it means, they can now use the method.
It isn't really important, whether the data were missing previously, returned bad or low variety data.
Because they either didn't use the method before (because it didn't work) or if they ran into any issues, they either reported it or at least know about the issues. And if they didn't notice any issues, then it wasn't an issue for them.

Just have a look at the locale PRs and have a look at them only getting the locale tag (plus a few fix labels).

**Pull request merged**
