### PR TITLE
docs: convert to typescript

### PR DESCRIPTION
**Pull request by Shinigami92**

### CODE REVIEW

**Comment by ST-DDT** [comment]
Merge after #659

**Review by ST-DDT — CHANGES_REQUESTED** [review]
This PR still has the issue with the changed file in `pnpm run docs:dev`.

**Comment by Shinigami92** [comment]
> This PR still has the issue with the changed file in `pnpm run docs:dev`.

Are you sure? Maybe GitHub cached something on your browser, please re-check this PR.

I checked locally:

1. pnpm run clean
2. revert pnpm-lock.yaml
3. pnpm install
4. pnpm run build
5. pnpm run docs:dev

no problems

**Review by ST-DDT — APPROVED** [review]
Looks like I tested an old version (bad vscode!).
Works as expected now.

**Review by ST-DDT — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Review by import-brain — APPROVED** [review]

**Pull request merged**
