### PR TITLE
fix: re-enable failing test on windows

### LINKED ISSUE #223: Test: Fix failing test finance in win32 system
### Describe the bug

The below test is failing in GitHub Workflow's CI and needs to be fixed.

This was discovered in #179

### Reproduction

Remove the conditional wrapper and see CI failing

### Additional Info

https://github.com/faker-js/faker/blob/80e8b3d4aec2e8944f7488a86f6b1ad4d2b2445d/test/finance.unit.js#L283-L302

### PR DESCRIPTION
**Pull request by ST-DDT**
I tried running the tests in my fork and it worked pretty fine when running there.
https://github.com/ST-DDT/faker/pull/1

### CODE REVIEW

**Comment by ST-DDT** [comment]
For some reason this seems to be working fine now.
Maybe we should wait a bit and rerun the pipeline later to ensure this isn't a flaky test result.
(I had a similar problem with one of my java applications before. The docker host ran into performance + port issues causing the tests to fail, but those were distributed more randomly)

**Review by Shinigami92 — DISMISSED** [review]

**Review by poyea — DISMISSED** [review]
Maintainers can re-run the jobs in the Actions tab in the future, if it's failing for some weird reasons (considering there's a large amount of individual tests).

**Comment by ST-DDT** [comment]
FFR: The test is failing at 19:26:27 UTC

**Comment by ST-DDT** [comment]
FFR: The test succeeded at 09:21 MEZ

**Comment by ST-DDT** [comment]
This probably gets obsolete once https://github.com/faker-js/faker/pull/235 is merged.

**Pull request closed without merging**
