### PR TITLE
ci: add release workflow

### LINKED ISSUE #268: Automatic npm publish on commit
### Clear and concise description of the problem

As a developer using faker I want to get the latest merged changes on npm so that I can get access to the latest changes without local npm linking.

Right now, it seems that tag creation is done manually (maybe?) and there are some changes that are not available on the published npm version.

### Suggested solution

We could setup some action to execute on master commits to automatically bump versions and publish to npm.

I've used https://www.npmjs.com/package/semantic-release in the past, config is a bit daunting but the result is pretty great.

Additional branches could be created to generate release candidate/alpha/beta releases as well (but personally, I don't really think this is useful).

### Alternative

An alternative would be to keep pushing tags manually but maybe do it at a higher frequency ?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DaviDevMod**
Hello, I randomly stumbled in this issue #268 while I was taking a look at your [project](https://github.com/orgs/faker-js/projects/2) to get some inspiration.

For the past few days I've been dealing with automating the releases of one of my project and as soon I saw the issue, I thought I could give some help.

I just ported the [changesets/changesets](https://github.com/changesets/changesets) solution for my yarn workspaces to your pnpm project.

I did so with the help of some documentation:
- [Using Changesets with pnpm](https://pnpm.io/using-changesets)
- [changesets/action](https://github.com/changesets/action)
- [.npmrc detection depends on HOME process env](https://github.com/changesets/action/issues/147)

I didn't fully tested the workflow because I would need a `secrets.GITHUB_TOKEN` and a `secrets.NPM_TOKEN`  but I am confident that it should work. Give it a try.

The way this should work is that whenever you want to add a changeset, you run `pnpm changeset` and follow the instructions.
Then commit the autogenerated changeset and push to `main`.
The push triggers a `release` workflow that will create a PR with the changeset, or if there was a PR already open it will just add commits to that PR.
Once you merge the PR, a new release of your package is automatically published to both NPM and GitHub.

You can customize stuff and probably you also want to adopt this beatiful [changeset-bot](https://github.com/apps/changeset-bot).

### CODE REVIEW

**Comment by DaviDevMod** [comment]
I guess the `prepublishOnly` script could be removed.
And you may also want to add some caching logic to the workflow, but I leave it up to you. It's a very light workflow which wouldn't even run as often as the others.

**Comment by ST-DDT** [comment]
Just to give you some feedback. We will discuss this in our team meeting next week.

**Comment by DaviDevMod** [comment]
@ST-DDT I do appreciate the feedback. Thank you.

**Comment by Shinigami92** [comment]
I currently not have the time to look into it to deep but one of my first questions would be if `standard-version` is still needed or if this also create it's own way of changelog 🤔 

Not to fully count that this PR will get merged some day, but we should use node 18 instead of 16 and you are right about that we may remove the `prepublishOnly` and `release` step unless otherwise needed.

**Comment by DaviDevMod** [comment]
@Shinigami92 yes it creates changelogs. I believe it would just add new ones at the top of you old CHANGELOG.md

When you make a commit that has a changeset, it gets committed as usual, but the workflow sees therre is a new changeset and creates (or updates) a PR which contains:
- the various additions to the CHANGELOG.md 
- the removal of all the changesets 
- a version bump in `package.json`.

You can modify the PR in any way, like changing the title or editing the commits.

Once the PR is merged you get the updated CHANGELOG.md and the version bump in `main`. The changesets are gone and a new release will be found on NPM and GitHub.

Now that I think about it, the workflow can run just for `.changeset/**`, there is no need for that `CHANGELOG.md`.
I am going to change the `paths` in the workflow and add the changes you mentioned.

**Comment by ST-DDT** [comment]
We will stay with the current way of generating changelogs.
Also this gotten stale, so closing for now.

**Comment by DaviDevMod** [comment]
That's alright, hope you find a workflow that fits your needs.

**Pull request closed without merging**
