### PR TITLE
docs: fix "browse api" button in light mode

### LINKED ISSUE #2626: Title and buttons on homepage have gone blue?
Has some CSS gone astray? Title is now blue and the Browse API button is quite hard to read.

https://fakerjs.dev/

Screenshot 2024-01-28 at 20 21 45

https://web.archive.org/web/20231129222728/https://fakerjs.dev/

Screenshot 2024-01-28 at 20 21 36

### PR DESCRIPTION
**Pull request by Shinigami92**
related to https://github.com/faker-js/faker/issues/2626

### CODE REVIEW

**Review by xDivisionByZerox — APPROVED** [review]
This "just" fixes the color for the API button in dark mode. Correct? IN that case I would not close #2626 after this is merged.

**Comment by Shinigami92** [comment]
> This "just" fixes the color for the API button in dark mode. Correct? IN that case I would not close #2626 after this is merged.

if it accidentally gets auto-closed, we will reopen it :+1:

**Comment by ST-DDT** [comment]
For me this is still blue!? 🤔 

grafik
grafik

**Comment by Shinigami92** [comment]
> For me this is still blue!? 🤔

you misunderstood the fix
the potential rebrand will be done in another PR not by me

**Comment by ST-DDT** [comment]
What does this PR do than? Because the button has the same color as prod

grafik

**Comment by ST-DDT** [comment]
This one?
grafik

**Comment by ST-DDT** [comment]
Please add a proper description to the PRs so that we don't have to guess what the PRs do.

**Review by ST-DDT — APPROVED** [review]

**Comment by Shinigami92** [comment]
@matthewmayer In your screenshots https://github.com/faker-js/faker/pull/2632#issue-2104433328 the button looks okay 🤔 
But the diff in your PR does not change the related style 👀 
Did you made a screenshot with this fix? Or did it magically work in our PR?!

**Comment by matthewmayer** [comment]
I tested my changes on top of this PR, assuming this PR would get merged first.

**Pull request merged**
