### PR TITLE
docs(string): improve documentation for length parameters

### LINKED ISSUE #2695: Improve DX for methods that use all memory
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

Using a big integer as min or max in `faker.string.numeric` in length options, is not handled gracefully and causes `Javascript heap out of memory` crash in V8. It should at least validate the inputs and provide a graceful exception message. Even better; provide big int support in options.

### Minimal reproduction code

```
const { faker } = require("@faker-js/faker");

const fake = {
    bigRange: faker.string.numeric({ length: { min: 1000000000, max: 2000000000 }})
}

console.log("bigRange:", fake.bigRange);
```

### Additional Context

_No response_

### Environment Info

```shell
System:
  OS: macOS (Apple silicon)
Binaries:
  Node: 20.9.0
  npm: 10.1.10
npmPackages:
  @faker-js/faker: 8.4.1
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes https://github.com/faker-js/faker/issues/2695#issuecomment-1968399853

- https://github.com/faker-js/faker/issues/2695#issuecomment-1968399853

The rest of the issue will be fixed in a separate PR.

---

Improves and unifies the documentation of the length parameter in the string module.

- [Current Documentation](https://next.fakerjs.dev/api/string.html)
- [Preview Documentation](https://deploy-preview-3216.fakerjs.dev/api/string.html)

### CODE REVIEW

**Review by xDivisionByZerox — APPROVED** [review]
While this is great for documentation purposes, I don't see how this fixes #2695 fully.

**Comment by ST-DDT** [comment]
It isnt meant to.
There is a second part to the issue, but I cannot tackle it without the first part.

- https://github.com/faker-js/faker/issues/2695#issuecomment-2432137627

**Comment by xDivisionByZerox** [comment]
> It isnt meant to.

I was nearly certain about this, but the current PR description said otherwise: 

> Fixes https://github.com/faker-js/faker/issues/2695#issuecomment-1968399853

**Comment by ST-DDT** [comment]
> I was nearly certain about this, but the current PR description said otherwise:
> 
> > Fixes [#2695 (comment)](https://github.com/faker-js/faker/issues/2695#issuecomment-1968399853)

The PR fixes the referenced comment, not the entire issue. I'll change the description to make it more obvious.

**Comment by ST-DDT** [comment]
Merging earlier to include in release

**Pull request merged**
