### PR TITLE
chore: update codeowners file

### PR DESCRIPTION
**Pull request by Shinigami92**
- Formatted the file a bit better
- Added maintainers also to docs, so one of them is just required (codeowners file works with `or`-condition in a line)

### CODE REVIEW

**Comment by Shinigami92** [comment]
We need to give the maintainers-docs group write access

**Review by ST-DDT — APPROVED** [review]
^

**Comment by Shinigami92** [comment]
Okay, let's wait on @damienwebdev and the write access for `maintainers-docs`

**Comment by Shinigami92** [comment]
Beside the fact that the docs owners doesn't work as expected, it will not break when I merge this...
So I will do that now

**Pull request merged**
