### PR TITLE
ci: add azure pipelines

### LINKED ISSUE #1: ci: Add Github Actions pipeline

### PR DESCRIPTION
**Pull request by griest024**
fixes #1

### CODE REVIEW

**Review by clarkerican — APPROVED** [review]

**Comment by Shinigami92** [comment]
Is there a specific reason why using azure pipelines instead of github workflows?

**Comment by griest024** [comment]
> Is there a specific reason why using azure pipelines instead of github workflows?

It made more sense when this was in the graycore namespace. As it is now, I think GH actions probably makes more sense

**Comment by damienwebdev** [comment]
Closing in favor of a Github Action.

**Comment by leonardsellem** [comment]
After reviewing the FakerJS GitHub discussions, no existing issues directly address deterministic unique data generation. Specifically:

- Issue #1785 (https://github.com/faker-js/faker/issues/1785) discusses the deprecation of helpers.unique, highlighting that relying solely on FakerJS for uniqueness is insufficient.
- General consensus from discussions suggests avoiding reliance solely on faker.seed() for uniqueness due to concurrency limitations.

Recommended approach based on these findings:
1. Avoid relying solely on faker.seed().
2. Implement explicit uniqueness checks using JavaScript Sets or Maps.
3. Generate unique identifiers (UUIDs) for critical fields.
4. Ensure database-level uniqueness constraints.

This approach will effectively resolve the duplicate providers issue.

**Pull request closed without merging**
