### PR TITLE
chore: delete old examples and doc folder

### PR DESCRIPTION
**Pull request by damienwebdev**
The new docs can be found in the `docs` folder.

### CODE REVIEW

**Comment by Shinigami92** [comment]
Good idea to delete them
Even if we need them, we can just access git history :+1:

**Comment by Shinigami92** [comment]
I see you also deleted the examples folder :thinking: 
We should look if there is somewhere a test or we need to write a test to test that it works in the browser.
Alternative we could say for now we don't support browser version :thinking: 

Did you also check that the `examples/browser/js/faker(.min).js` files are not generated anymore by scripts?
Maybe we can also remove some stuff from gitignore and such.

**Comment by JessicaSachs** [comment]
I plan to write integration tests for parts of the docs at least. We can use the playground for that.

**Comment by damienwebdev** [comment]
@Shinigami92 I did verify the removal of the examples from the gulpfile. https://github.com/faker-js/faker/pull/155/files#diff-5389b9382804b62e7e964159df7c0c792dffb0705a48429d96d1aacd830aef09L28

**Review by import-brain — APPROVED** [review]

**Review by import-brain — DISMISSED** [review]

**Comment by Shinigami92** [comment]
image

Let's rebase this PR after we merged #235

**Comment by Shinigami92** [comment]
I additionally cleaned up some files, so this is not just deleting the `doc` and `examples` folder but also format not formatted files and removed the old `logo.png`

**Review by Shinigami92 — APPROVED** [review]

**Review by doughlass — APPROVED** [review]

**Review by prisis — APPROVED** [review]

**Pull request merged**
