### PR TITLE
fix: datatype.datetime should use static boundaries

### LINKED ISSUE #334: datatype.datetime seed might not be working
### Describe the bug

There was this comment in the jsdoc
https://github.com/faker-js/faker/blob/60b71fd257c2b95a6997f5aac516b88327a78f4b/src/datatype.ts#L92-L98

We are not sure if this is true or not, however this method relies underneath on `datatype.number` which might be also affected.

Discussed here: https://discord.com/channels/929487054990110771/929544761122111498/936559737540071434

### Reproduction

Needs investigation

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes #334 

`new Date().setFullYear(...)` does not return a consistent value, as the actual time is not fixed an thus depends on the execution time + timezone. 

This PR uses UTC based static values instead.

### CODE REVIEW

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
Nice catch and fix! We use `new Date()` in `date.te` too, and I think I have seen some test failing around the midnight where the local time zone was the next day vs utc. Maybe it would be worth to apply it over there too?

**Review by pkuczynski — APPROVED** [review]

**Comment by Shinigami92** [comment]
Oh my god (╯°□°)╯︵ ┻━┻

**Comment by ST-DDT** [comment]
> Nice catch and fix! We use `new Date()` in `date.te` too, and I think I have seen some test failing around the midnight where the local time zone was the next day vs utc. Maybe it would be worth to apply it over there too?

The date module uses either `new Date()` with refers to a relative date or uses the `dateRef` parameter.
So it should be stable. If you catch a failing test, please report it so that we can analyze it and check only the related methods.

**Comment by ST-DDT** [comment]
This needs to be rebased after #344 is merged.

**Comment by ST-DDT** [comment]
Rebased

**Review by Shinigami92 — DISMISSED** [review]

**Review by pkuczynski — DISMISSED** [review]
Thats what I mentioned the other day. Cool that you fixed it :)

**Review by Shinigami92 — APPROVED** [review]

**Review by Shinigami92 — DISMISSED** [review]

**Review by Shinigami92 — DISMISSED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Review by prisis — APPROVED** [review]

**Pull request merged**
