### PR TITLE
chore: remove comments in tsconfig.json

### PR DESCRIPTION
**Pull request by bdb2381**
JSON doesn't support comments. This PR removes the comments.

One downstream impact of these comments is Snyk fails to parse the JSON file.  https://jsoneditoronline.org/indepth/parse/json-comments/ for some details

### CODE REVIEW

**Comment by Shinigami92** [comment]
Please note that tsconfig.json is officially written in jsonc

- https://github.com/microsoft/TypeScript/issues/4987
- https://github.com/Microsoft/vscode/issues/50974

So comments are officially allowed, based on what TypeScript allows

---

Theoretically we could remove these values anyway, but it might be that we would write other comments into this file anyway in a later phase for any reason

So IMO the problem is not on our side but on `Snyk` as they should use a jsonc / json5 parser to correctly read these kind of files

**Comment by bdb2381** [comment]
That is new learning, jsonc. Thank you for the docs. I'll review so I have a better understanding. 

Agreed it is handy to have comments. And agree it is something Snyk should handle as Faker isn't the only thing Snyk fails to parse. I'll work with an AE at Snyk for it.

**Comment by xDivisionByZerox** [comment]
> Theoretically we could remove these values anyway, but it might be that we would write other comments into this file anyway in a later phase for any reason

I suggest explicitly setting or removing them. Even if comments are technically allowed, the one in question do not serve any purpose currently.

**Comment by ST-DDT** [comment]
I agree with @xDivisionByZerox 's reasoning here.
These should either be activated or removed (or should have a comment why they are there).

Since @Shinigami92 added them in https://github.com/faker-js/faker/pull/651 I would like to hear his original intention with those lines and suggestions whether to enable or remove them.

**Comment by Shinigami92** [comment]
> Since @Shinigami92 added them in #651 I would like to hear his original intention with those lines and suggestions whether to enable or remove them.

It's exactly what the PR title is intended to say: **partially** activate strict mode
At the end it would be very nice to have our project fully `strict` (this is a ts flag that can be set to `true`)
But there were some issues and they can partially get solved one by one, one after another...
And at the end, erase all the partial flags and just set `strict: true`

**Comment by ST-DDT** [comment]
> At the end it would be very nice to have our project fully `strict` (this is a ts flag that can be set to `true`)
> But there were some issues and they can partially get solved one by one, one after another...
> And at the end, erase all the partial flags and just set `strict: true`

I created an issue for each of them:

- https://github.com/faker-js/faker/issues/1834
- https://github.com/faker-js/faker/issues/1835
- https://github.com/faker-js/faker/issues/1836
- https://github.com/faker-js/faker/issues/1837
- https://github.com/faker-js/faker/issues/1838

IMO this PR is now obsolete, since we want to actually turn on those lines.
What do you think?

**Review by Shinigami92 — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]
IMO we can still merge this as an appreciation towards @bdb2381 for pointing out those settings.

**Comment by ST-DDT** [comment]
Since @Shinigami92 already started working on them I think this will only cause merge conflicts.

I will close this, but thanks for bringing this to our attention.

**Comment by Shinigami92** [comment]
On the one side, we could merge it, on the other side, it is more or less irrelevant as we wont release something just for this right now and therefore it would take month(s) anyway to land in "prod"

**Pull request merged**
